#!/usr/bin/env python

# Squeezebox client
# copyright (c) 2013 tang
 
import sys
import agoclient
import pylmsserver
import pylmsplaylist
import pylmslibrary
import threading
import time
import logging

server = None
playlist = None
library = None
client = None
states = {}

STATE_OFF = 0
STATE_PLAY = 50
STATE_STOP = 100
STATE_PAUSE = 150
STATE_ON = 255

#logging.basicConfig(filename='agosqueezebox.log', level=logging.INFO, format="%(asctime)s %(levelname)s : %(message)s")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s : %(message)s")

#utils
def getPlayer(player_id):
    """Return player according to player_id"""
    return playlist.get_server().get_player(player_id)

def quit(msg):
    """Exit application"""
    global playlist
    if playlist:
        playlist.stop()
        playlist = None
    logging.fatal(msg)
    sys.exit(0)

#squeezebox callbacks
def play_callback(player_id, track_title, playlist_index):
    #if player is off or player is already playing, kick this callback
    if states.has_key(player_id) and states[player_id]!=STATE_OFF and states[player_id]!=STATE_PLAY:
        logging.info('callback PLAY: %s' % player_id)
        states[player_id] = STATE_PLAY
        emit_play(player_id)
def stop_callback(player_id):
    #if player is off, kick this callback
    if states.has_key(player_id) and states[player_id]!=STATE_OFF:
        logging.info('callback STOP: %s' % player_id)
        states[player_id] = STATE_STOP
        emit_stop(player_id)
def pause_callback(player_id):
    #if player is off, kick this callback
    if states.has_key(player_id) and states[player_id]!=STATE_OFF:
        logging.info('callback PAUSE: %s' % player_id)
        states[player_id] = STATE_PAUSE
        emit_pause(player_id)
def on_callback(player_id):
    logging.info('callback ON: %s' % player_id)
    states[player_id] = STATE_ON
    emit_on(player_id)
def off_callback(player_id):
    logging.info('callback OFF: %s' % player_id)
    states[player_id] = STATE_OFF
    emit_off(player_id)


#emit function
def emit_play(internalid):
    client.emitEvent(internalid, "event.mediaplayer.statechanged", "play", "")
    client.emitEvent(internalid, "event.device.statechanged", str(STATE_PLAY), "")
def emit_stop(internalid):
    client.emitEvent(internalid, "event.mediaplayer.statechanged", "stop", "")
    client.emitEvent(internalid, "event.device.statechanged", str(STATE_STOP), "")
def emit_pause(internalid):
    client.emitEvent(internalid, "event.mediaplayer.statechanged", "pause", "")
    client.emitEvent(internalid, "event.device.statechanged", str(STATE_PAUSE), "")
def emit_on(internalid):
    client.emitEvent(internalid, "event.device.statechanged", str(STATE_ON), "")
def emit_off(internalid):
    client.emitEvent(internalid, "event.device.statechanged", str(STATE_OFF), "")

#init
try:
    #connect agoclient
    client = agoclient.AgoConnection("squeezebox")

    #read configuration
    host = agoclient.getConfigOption("squeezebox", "host", "127.0.0.1")
    port = int(agoclient.getConfigOption("squeezebox", "port", "9090"))
    login = agoclient.getConfigOption("squeezebox", "login", "")
    passwd = agoclient.getConfigOption("squeezebox", "password", "")
    logging.info("Config: %s@%s:%d" % (login, host, port))
    
    #connect to squeezebox server
    logging.info('Creating LMSServer...')
    server = pylmsserver.LMSServer(host, port, login, passwd)
    server.connect()
    
    #connect to notifications server
    logging.info('Creating LMSPlaylist...')
    library = pylmslibrary.LMSLibrary(host, port, login, passwd)
    playlist = pylmsplaylist.LMSPlaylist(library, host, port, login, passwd)
    #play, pause, stop, on, off, add, del, move, reload
    playlist.set_callbacks(play_callback, pause_callback, stop_callback, on_callback, off_callback, None, None, None, None)
    playlist.start()
    
except Exception as e:
    #init failed
    quit('Init failed, exit now. (%s)' % str(e))

    

#Set message handler
#state values:
# - 0 : OFF
# - 255 : ON
# - 50 : PLAYING
# - 100 : STOPPED
# - 150 : PAUSED
def messageHandler(internalid, content):
    logging.info('messageHandler: %s, %s' % (internalid,content))

    #get player
    player = getPlayer(internalid)
    if not player:
        logging.error('Player %s not found!' % internalid)
        return None
    
    if "command" in content:
        if content["command"] == "on":
            logging.info("Command ON: %s" % internalid)
            player.on()
        elif content["command"] == "off":
            logging.info("Command OFF: %s" % internalid)
            player.off()
        elif content["command"] == "play":
            logging.info("Command PLAY: %s" % internalid)
            player.play()
        elif content["command"] == "pause":
            logging.info("Command PAUSE: %s" % internalid)
            player.pause()
        elif content["command"] == "stop":
            logging.info("Command STOP: %s" % internalid)
            player.stop()
client.addHandler(messageHandler)

#discover players
try:
    logging.info('Discovering players:')
    for p in server.get_players():
        logging.info("  Add player : %s[%s]" % (p.name, p.mac))
        client.addDevice(p.mac, "squeezebox")
except Exception as e:
    quit('Failed to discover players. Exit now. (%s)' % str(e))

#get players states
logging.info('Get current players states:')
try:
    for p in server.get_players():
        if not p.get_is_on():
            #player is off
            logging.info('  Player %s[%s] is off' % (p.name, p.mac))
            states[p.mac] = STATE_OFF
            emit_off(p.mac)
        else:
            #player is on
            mode = p.get_mode()
            if mode=='stop':
                logging.info('  Player %s[%s] is stopped' % (p.name, p.mac))
                states[p.mac] = STATE_STOP
                emit_stop(p.mac)
            elif mode=='play':
                logging.info('  Player %s[%s] is playing' % (p.name, p.mac))
                states[p.mac] = STATE_PLAY
                emit_play(p.mac)
            elif mode=='pause':
                logging.info('  Player %s[%s] is paused' % (p.name, p.mac))
                states[p.mac] = STATE_PAUSE
                emit_pause(p.mac)
            else:
                logging.info('  Player %s[%s] is on' % (p.name, p.mac))
                states[p.mac] = STATE_ON
                emit_on(p.mac)
except Exception as e:
    quit('Failed to get player status. Exit now. (%s)' % str(e))

#run agoclient
logging.info('Running agoclient...')
client.run()


