all:

install:
	$(INSTALL_DIR) $(BINDIR)
	$(INSTALL_PROGRAM) agosqueezebox $(BINDIR)
	$(INSTALL_PROGRAM) pylmsserver.py $(BINDIR)
	$(INSTALL_PROGRAM) pylmslibrary.py $(BINDIR)
	$(INSTALL_PROGRAM) pylmsplayer.py $(BINDIR)
	$(INSTALL_PROGRAM) pylmsplaylist.py $(BINDIR)
	$(INSTALL_DIR) $(CONFDIR)

clean:
