all:

install:
	$(INSTALL_DIR) $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) agosqueezebox $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) pylmsserver.py $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) pylmslibrary.py $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) pylmsplayer.py $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) pylmsplaylist.py $(DESTDIR)$(BINDIR)
	$(INSTALL_DIR) $(DESTDIR)$(CONFDIR)

clean:
