all:

install:
	$(INSTALL_DIR) $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) core.py $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) commands.py $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) agoiscp.py $(DESTDIR)$(BINDIR)

clean:

