all:

install:
	$(INSTALL_DIR) $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) agoalert.py $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) pushbullet.py $(DESTDIR)$(BINDIR)
	$(INSTALL_DIR) $(DESTDIR)$(CONFDIR)

clean:
