version: 0.1
commands:
  "on":
    name: turn on
  "off":
    name: turn off
  "allon":
    name: turn all on
  "alloff":
    name: turn all off
  "run":
    name: run
  push:
    name: push button
  setvariable:
    name: set global variable
    parameters:
      value:
         name: value to set
         type: variant
      variable:
         name: name of the variable
         type: string
  delvariable:
    name: delete global variable
    parameters:
      variable:
         name: name of the variable
         type: string
  settemperature:
    name: set temperature
    parameters:
      temperature:
        name: temperature to set
        type: float
      mode:
        name: setpoint mode
        type: option
        options: ["auto", "cool", "heat"]
  setthermostatmode:
    name: adjust thermostat mode
    parameters:
      mode:
        name: thermostat mode to set
        type: option
        options: ["heat", "cool", "auto"]
  setthermostatfanmode:
    name: adjust thermostat fan mode
    parameters:
      mode:
        name: fan mode to set
        type: option
        options: ["on", "off", "auto"]
  dial:
    name: dial number
    parameters:
      number:
        name: number to dial
        type: string 
  setlevel:
    name: set level
    parameters:
      level:
        name: level to set
        type: integer
        range: [0, 100]
  setchannel:
    name: set channel
    parameters:
      channel:
        name: channel to set
        type: integer
        range: [0, 9999]
  setcolor:
    name: set color
    parameters:
      red:
        name: level for red color
        type: integer
        range: [0, 100]
      green:
        name: level for red color
        type: integer
        range: [0, 100]
      blue:
        name: level for red color
        type: integer
        range: [0, 100]
  sethousemode:
    name: set the house mode
    parameters:
      mode:
        name: house mode
        type: option
        options: ["unarmed", "armed_athome", "armed_away", "entertaining", "sleeping", "armed_extendedaway"]
      pin:
        name: security pin
        type: integer
        range: [0, 999999]
  triggerzone:
    name: trigger security zone
    parameters:
      zone:
        name: zone to trigger
        type: string
  setzones:
    name: define zones
  sendir:
    name: send infrared remote code
    parameters:
      ircode:
        name: infrared code to send
        type: string
  getvideoframe:
    name: get video frame
  mute:
    name: mute audio
  unmute:
    name: unmute audio
  mutetoggle:
    name: toggle mute
  vol+:
    name: volume up
  vol-:
    name: volume down
  chan+:
    name: next channel
  chan-:
    name: previous channel
  setinput:
    name: input selector
    type: option
    options: ["video1", "video1", "video3", "video4", "video5", "video6", "dvd", "fm", "am", "usb", "net", "up", "down"]
  play:
    name: play media
  pause:
    name: pause media
  stop:
    name: stop
  addnode:
    name: add a node
  removenode:
    name: remove a node
  addcontroller:
    name: add a controller
  removecontroller:
    name: remove a controller
  addassociation:
    name: add association
    parameters:
      node:
        name: node 
        type: integer
      group:
        name: group
        type: integer
      target:
        name: target
        type: integer
  removeassociation:
    name: remove association
    parameters:
      node:
        name: node 
        type: integer
      group:
        name: group
        type: integer
      target:
        name: target
        type: integer
  setconfigparam:
    name: configure parameter
    parameters:
      node:
        name: node 
        type: integer
      param:
        name: parameter number
        type: integer
      value:
        name: value to set
        type: integer
      size:
        name: size of value
        type: integer
  downloadconfig:
    name: receive network
  cancel:
    name: cancel operation
  saveconfig:
    name: save network config
  reset:
    name: reset network info
    parameters:
      name: confirm
      type: boolean
  getepg:
    name: get electronic program guide
  sendmail:
    name: send an email
    parameters:
      to:
        name: recipient
        type: string
      body:
        name: message body
        type: string
      subject:
        name: message subject
        type: string
  getdata:
    name: get data from datalogger
    parameters:
      startdate:
        name: start date
        type: string
      enddate:
        name: end date
        type: string
  getdeviceenvironments:
    name: get environments for device from datalogger
  setevent:
    name: create new event
  getevent:
    name: get event
  delevent:
    name: delete event
  setscenario:
    name: create scenario
  getscenario:
    name: get scenario
  delscenario:
    name: delete scenario
  displaymessage:
    name: display a message
    parameters:
      duration:
        name: duration
        type: integer
      line2:
        name: line2
        type: string
      line1:
        name: line1
        type: string
  teachframe:
    name: send a teach frame
    parameters:
      channel:
        name: channel to use
        type: integer
      profile:
        name: enocean profile to use
        type: option
        options: ["central command dimming"]
  setlearnmode:
    name: enter learn mode
    parameters:
      mode:
        name: learn mode
        type: option
        options: ["start", "stop"]
  setidbase:
    name: set enocean id base
    parameters:
      idbase:
        name: id base
        type: integer
  adddevice:
    name: add device
    parameters:
      type:
        name: device type
        type: string
      param1:
        name: param1
        type: string
      param2:
        name: param2
        type: string
      param3:
        name: param3
        type: string
  status:
    name: get device status
  forcestate:
    name: force device state
    parameters:
      device:
        name: device internalid
        type: string
      state:
        name: device state
        type: string
  getdevices:
    name: get all devices
  setconfig:
    name: set config
    parameters:
      param1:
        name: parameter1
        type: string
      param2:
        name: parameter2
        type: string
      param3:
        name: parameter3
        type: string
      param4:
        name: parameter4
        type: string
      param5:
        name: parameter5
        type: string
  test:
    name: test
    parameters:
      param1:
        name: parameter1
        type: string
      param2:
        name: parameter2
        type: string
      param3:
        name: parameter3
        type: string
      param4:
        name: parameter4
        type: string
      param5:
        name: parameter5
        type: string
  sendalert:
    name: send alert
    parameters:
      type:
        name: alert type
        type: option
        options: ['mail', 'sms', 'push', 'twitter', 'gtalk']
      param1:
        name: parameter1
        type: string
      param2:
        name: parameter2
        type: string
      param3:
        name: parameter3
        type: string
      param4:
        name: parameter4
        type: string
      param5:
        name: parameter5
        type: string
devicetypes:
  enoceancontroller:
    name: enocean controller
    description: internal device to manage the enocean network
    commands: [teachframe, setlearnmode, setidbase]
  dataloggercontroller:
    name: datalogger controller
    description: internal device to control the datalogger
    commands: [delvariable]
  dataloggercontroller:
    name: datalogger controller
    description: internal device to control the datalogger
    commands: [getdata, getdeviceenvironments]
  eventcontroller:
    name: event controller
    description: internal device to control the events
    commands: [setevent, getevent, delevent]
  scenariocontroller:
    name: scenario controller
    description: internal device to control the scenarios
    commands: [setscenario, getscenario, delscenario, run]
  smtpgateway:
    name: mail gateway
    description: used to send emails
    commands: [sendmail]
  agocontroller:
    name: resolver controller
    description: internal device to control the resolver
    commands: [setvariable, delvariable]
  pushbutton:
    name: Pushbutton
    description: momentary switch
    commands: [push]
  hdmicec:
    name: HDMI CEC interface
    description: control devices on the HDMI bus
    commands: [alloff]
  infaredblaster:
    name: infraredblaster
    description: send infrared remote commands
    commands: [sendir]
  phone:
    name: telephone
    description: a phone
    commands: [dial] 
  zwavecontroller:
    name: z-wave interface
    description: z-wave interface from agozwave
    commands: [allon, alloff, addnode, removenode, addcontroller, removecontroller, addassociation, removeassociation, setconfigparam, downloadconfig, cancel, saveconfig, reset]
  securitycontroller:
    name: security system
    description: ago control security system module
    commands: [sethousemode, triggerzone, setzones]
  scenario:
    name: scene
    description: execute scenarios
    commands: ["on"]
  event:
    name: event handler
    description: respond to events
    commands: []
  binarysensor:
    name: binary sensor
    description: sensor for on off values
    commands: []
  multilevelsensor:
    name: multilevel sensor
    description: sensor for multilevel values
    commands: [reset]
  smokedetector:
    name: smoke detector
    description: smoke detector
    commands: []
  camera:
    name: Camera
    description: Surveillance camera
    commands: [getvideoframe]
  avreceiver:
    name: AV receiver
    description: AV receiver
    commands: ["on", "off", mute, unmute, mutetoggle, vol+, vol-, setinput, setlevel]
  tv:
    name: TV
    description: TV
    commands: ["on", "off", mute, unmute, vol+, vol-, chan+, chan-, setchannel, setinput, setlevel]
  dimmerrgb:
    name: RGB dimmer
    description: allows to set different colors
    commands: ["on", "off", setlevel, setcolor]
  controller:
    name: controller
    description: generic controller
    commands: []
  thermostat:
    name: thermostat
    description: controls temperature
    commands: [settemperature, setthermostatmode, setthermostatfanmode]
  drapes:
    name: drapes
    description: window drapes or blinds
    commands: ["on", "off", stop, setlevel]
  dimmer:
    name: dimmer
    description: light dimmmer
    commands: ["on", "off", setlevel]
  switch:
    name: switch
    description: simple on off switch
    commands: ["on", "off"]
  squeezebox:
    name: Squeezebox Player
    description: Plays music
    commands: ["on", "off", play, pause, stop, displaymessage]
  squeezeboxserver:
    name: Squeezebox Server
    description: Squeezebox player manager
    commands: ["allon", "alloff", displaymessage]
  settopbox:
    name: Set top box
    description: Receives TV Service
    commands: ["on", "off", mute, unmute, mutetoggle, vol+, vol-, setlevel, setchannel, getepg]
  ipx800controller:
    name: IPX800 board controller
    description: Internal device to control IPX800 boards
    commands: [adddevice]
  ipx800v3board:
    name: IPX800v3 relay board
    description: Ethernet relay board
    commands: [adddevice, allon, alloff, status, forcestate, getdevices]
  alertcontroller:
    name: alert controller
    description: internal device to control the alerts
    commands: [status, test, sendalert, setconfig]
values:
  level:
    name: level
    description: level value
  channel:
    name: channel
    description: channel number
  devicetype:
    name: device type
    description: device type
  uuid:
    name: uuid
    description: unique id
  product:
    name: product
    description: product
  manufacturer:
    name: manufacturer
    description: manufacturer
  unit:
    name: unit
    description: unit of a value
  internalid:
    name: internal id for a device
    description: internal id used by interface device
  handled-by:
    name: instance name
    descroption: instance which handles the device
  minute:
    name: minute
    description: minute
  hour:
    name: hour
    description: hour
  second:
    name: second
    description: second
  month:
    name: month
    description: month
  day:
    name: day
    description: day
  year:
    name: year
    description: year
  weekday:
    name: weekday
    description: day of week
  yday:
    name: yday
    description: nth day of year
  callerid:
    name: caller identity
    description: the identity of a caller
  extension:
    name: phone extension
    description: extension being called
events:
  event.telecom.call:
    description: a call is originating
    parameters: [uuid, callerid, extension]
  event.telecom.hangup:
    description: call hung up
    parameters: [uuid]
  event.device.announce:
    description: announces a device to the resolver
    parameters: [devicetype, uuid, product, internal-id]
  event.device.statechanged:
    description: announces a status change of a device
    parameters: [level, uuid]
  event.environment.counterchanged:
    description: counter has changed
    parameters: [level, uuid]
  event.environment.temperaturechanged:
    description: temperature has changed
    parameters: [level, unit, uuid]
  event.environment.brightnesschanged:
    description: brightness has changed
    parameters: [level, unit, uuid]
  event.environment.humiditychanged:
    description: humidity has changed
    parameters: [level, unit, uuid]
  event.security.sensortriggered:
    description: sensor was triggererd
    parameters: [level, uuid]
  event.environment.sunset:
    description: sun has set
  event.environment.sunrise:
    description: sun did rise
  event.environment.timechanged:
    description: time did advance
    parameters: [minute, hour, month, day, year, weekday, yday]
  event.mediaplayer.statechanged:
    description: mediaplayer changed play state
    parameters: [new_state]
  event.security.intruderalert:
    description: intruder alarm
    parameters: [uuid]
  event.environment.energychanged:
    description: energy has changed
    parameters: [level, uuid]
units:
  degC:
    label: "°C"
    description: degree celcius
  percent:
    label: "%"
    description: percent value
