version: 0.1
commands:
  "on":
    name: turn on
  "off":
    name: turn off
  "allon":
    name: turn all on
  "alloff":
    name: turn all off
  "run":
    name: run
  push:
    name: push button
  setvariable:
    name: set global variable
    parameters:
      value:
         name: value to set
         type: variant
      variable:
         name: name of the variable
         type: string
  delvariable:
    name: delete global variable
    parameters:
      variable:
         name: name of the variable
         type: string
  settemperature:
    name: set temperature
    parameters:
      temperature:
        name: temperature to set
        type: float
      mode:
        name: setpoint mode
        type: option
        options: ["auto", "cool", "heat"]
  setthermostatmode:
    name: adjust thermostat mode
    parameters:
      mode:
        name: thermostat mode to set
        type: option
        options: ["heat", "cool", "auto"]
  setthermostatfanmode:
    name: adjust thermostat fan mode
    parameters:
      mode:
        name: fan mode to set
        type: option
        options: ["on", "off", "auto"]
  dial:
    name: dial number
    parameters:
      number:
        name: number to dial
        type: string 
  setlevel:
    name: set level
    parameters:
      level:
        name: level to set
        type: integer
        range: [0, 100]
  setchannel:
    name: set channel
    parameters:
      channel:
        name: channel to set
        type: integer
        range: [0, 9999]
  setcolor:
    name: set color
    parameters:
      red:
        name: level for red color
        type: integer
        range: [0, 100]
      green:
        name: level for red color
        type: integer
        range: [0, 100]
      blue:
        name: level for red color
        type: integer
        range: [0, 100]
  sethousemode:
    name: set the house mode
    parameters:
      mode:
        name: house mode
        type: option
        options: ["unarmed", "armed_athome", "armed_away", "entertaining", "sleeping", "armed_extendedaway"]
      pin:
        name: security pin
        type: integer
        range: [0, 999999]
  triggerzone:
    name: trigger security zone
    parameters:
      zone:
        name: zone to trigger
        type: string
  setzones:
    name: define zones
  sendir:
    name: send infrared remote code
    parameters:
      ircode:
        name: infrared code to send
        type: string
  getvideoframe:
    name: get video frame
  mute:
    name: mute audio
  unmute:
    name: unmute audio
  mutetoggle:
    name: toggle mute
  vol+:
    name: volume up
  vol-:
    name: volume down
  chan+:
    name: next channel
  chan-:
    name: previous channel
  setinput:
    name: input selector
    type: option
    options: ["video1", "video1", "video3", "video4", "video5", "video6", "dvd", "fm", "am", "usb", "net", "up", "down"]
  play:
    name: play media
  pause:
    name: pause media
  stop:
    name: stop media
  addnode:
    name: add a node
  removenode:
    name: remove a node
  addcontroller:
    name: add a controller
  removecontroller:
    name: remove a controller
  addassociation:
    name: add association
    parameters:
      node:
        name: node 
        type: integer
      group:
        name: group
        type: integer
      target:
        name: target
        type: integer
  removeassociation:
    name: remove association
    parameters:
      node:
        name: node 
        type: integer
      group:
        name: group
        type: integer
      target:
        name: target
        type: integer
  setconfigparam:
    name: configure parameter
    parameters:
      node:
        name: node 
        type: integer
      param:
        name: parameter number
        type: integer
      value:
        name: value to set
        type: integer
      size:
        name: size of value
        type: integer
  downloadconfig:
    name: receive network
  cancel:
    name: cancel operation
  saveconfig:
    name: save network config
  reset:
    name: reset network info
    parameters:
      name: confirm
      type: boolean
  getepg:
    name: get electronic program guide
  sendmail:
    name: send an email
    parameters:
      to:
        name: recipient
        type: string
      body:
        name: message body
        type: string
      subject:
        name: message subject
        type: string
  getdata:
    name: get data from datalogger
    parameters:
      startdate:
        name: start date
        type: string
      enddate:
        name: end date
        type: string
  getdeviceenvironments:
    name: get environments for device from datalogger
  setevent:
    name: create new event
  getevent:
    name: get event
  delevent:
    name: delete event
  setscenario:
    name: create scenario
  getscenario:
    name: get scenario
  delscenario:
    name: delete scenario
  displaymessage:
    name: display a message
    parameters:
      duration:
        name: duration
        type: integer
      line2:
        name: line2
        type: string
      line1:
        name: line1
        type: string
  teachframe:
    name: send a teach frame
    parameters:
      channel:
        name: channel to use
        type: integer
      profile:
        name: enocean profile to use
        type: option
        options: ["central command dimming"]
  setlearnmode:
    name: enter learn mode
    parameters:
      mode:
        name: learn mode
        type: option
        options: ["start", "stop"]
  setidbase:
    name: set enocean id base
    parameters:
      idbase:
        name: id base
        type: integer
  addipx800:
    name: add IPX800 board
    parameters:
      ip:
        name: IPX800 ip address
        type: string
  addswitch:
    name: add switch (use 1 relay)
    parameters:
      relayid:
        name: relay id
        type: option
        options: ['output1', 'output2', 'output3', 'output4', 'output5', 'output6', 'output7', 'output8']
  addshutter:
    name: add shutter (use 2 relays)
    parameters:
      relayopen:
        name: relay open
        type: option
        options: ['output1', 'output2', 'output3', 'output4', 'output5', 'output6', 'output7', 'output8']
      relayclose:
        name: relay close
        type: option
        options: ['output1', 'output2', 'output3', 'output4', 'output5', 'output6', 'output7', 'output8']
  addanalog:
    name: add analog device (use 1 analog input)
    parameters:
      analogid:
        name: analog id
        type: option
        options: ['analog1', 'analog2', 'analog3', 'analog4']
      type:
        name: analog type
        type: option
        options: ['temperature', 'humidity', 'volt', 'light']
  addcounter:
    name: add counter device (use 1 counter)
    parameters:
      counterid:
        name: counter id
        type: option
        options: ['counter1', 'counter2', 'counter3']
  open:
    name: open
  close:
    name: close
  allopen:
    name: open all
  allclose:
    name: close all
  forcestate:
    name: force state
    parameters:
      state:
        name: relay state
        type: option
        options: ['on/open', 'off/close']
  resetcounter:
    name: reset counter
  twitterurl:
    name: get twitter authorization url
  twitteraccesscode:
    name: set twitter access code
    parameters:
      code:
        name: code
        type: string
  twittertest:
    name: send test tweet
  twittersend:
    name: send tweet
    parameters:
      tweet:
        name: tweet
        type: string
  mailconfig:
    name: set mail config
    parameters:
      smtp:
        name: smtp server
        type: string
      sender:
        name: email of sender
        type: string
  mailtest:
    name: send test email
    parameters:
      email:
        name: your email
        type: string
  mailsend:
    name: send email
    parameters:
      tos:
        name: list of email recipient (coma separated)
        type: string
      subject:
        name: email subject
        type: string
      content:
        name: email content
        type: string
  smsconfig:
    name: set SMS config
    parameters:
      username:
        name: username
        type: string
      password:
        name: password
        type: string
  smstest:
    name: send test SMS
  smssend:
    name: send SMS
    parameters:
      to:
        name: SMS recipient
        type: string
      text:
        name: SMS message
        type: string
  gtalkconfig:
    name: set GTalk config
    parameters:
      username:
        name: username
        type: string
      password:
        name: password
        type: string
  gtalktest:
    name: send test message on GTalk
  gtalksend:
    name: send GTalk message
    parameters:
      to:
        name: GTalk recipient
        type: string
      message:
        name: GTalk message
        type: string
  alertstatus:
    name: status of all alert modules
devicetypes:
  enoceancontroller:
    name: enocean controller
    description: internal device to manage the enocean network
    commands: [teachframe, setlearnmode, setidbase]
  dataloggercontroller:
    name: datalogger controller
    description: internal device to control the datalogger
    commands: [delvariable]
  dataloggercontroller:
    name: datalogger controller
    description: internal device to control the datalogger
    commands: [getdata, getdeviceenvironments]
  eventcontroller:
    name: event controller
    description: internal device to control the events
    commands: [setevent, getevent, delevent]
  scenariocontroller:
    name: scenario controller
    description: internal device to control the scenarios
    commands: [setscenario, getscenario, delscenario, run]
  smtpgateway:
    name: mail gateway
    description: used to send emails
    commands: [sendmail]
  agocontroller:
    name: resolver controller
    description: internal device to control the resolver
    commands: [setvariable, delvariable]
  pushbutton:
    name: Pushbutton
    description: momentary switch
    commands: [push]
  hdmicec:
    name: HDMI CEC interface
    description: control devices on the HDMI bus
    commands: [alloff]
  infaredblaster:
    name: infraredblaster
    description: send infrared remote commands
    commands: [sendir]
  phone:
    name: telephone
    description: a phone
    commands: [dial] 
  zwavecontroller:
    name: z-wave interface
    description: z-wave interface from agozwave
    commands: [allon, alloff, addnode, removenode, addcontroller, removecontroller, addassociation, removeassociation, setconfigparam, downloadconfig, cancel, saveconfig, reset]
  securitycontroller:
    name: security system
    description: ago control security system module
    commands: [sethousemode, triggerzone, setzones]
  scenario:
    name: scene
    description: execute scenarios
    commands: ["on"]
  event:
    name: event handler
    description: respond to events
    commands: []
  binarysensor:
    name: binary sensor
    description: sensor for on off values
    commands: []
  multilevelsensor:
    name: multilevel sensor
    description: sensor for multilevel values
    commands: []
  smokedetector:
    name: smoke detector
    description: smoke detector
    commands: []
  camera:
    name: Camera
    description: Surveillance camera
    commands: [getvideoframe]
  avreceiver:
    name: AV receiver
    description: AV receiver
    commands: ["on", "off", mute, unmute, mutetoggle, vol+, vol-, setinput, setlevel]
  tv:
    name: TV
    description: TV
    commands: ["on", "off", mute, unmute, vol+, vol-, chan+, chan-, setchannel, setinput, setlevel]
  dimmerrgb:
    name: RGB dimmer
    description: allows to set different colors
    commands: ["on", "off", setlevel, setcolor]
  controller:
    name: controller
    description: generic controller
    commands: []
  thermostat:
    name: thermostat
    description: controls temperature
    commands: [settemperature, setthermostatmode, setthermostatfanmode]
  drapes:
    name: drapes
    description: window drapes or blinds
    commands: ["on", "off", setlevel]
  dimmer:
    name: dimmer
    description: light dimmmer
    commands: ["on", "off", setlevel]
  switch:
    name: switch
    description: simple on off switch
    commands: ["on", "off"]
  squeezebox:
    name: Squeezebox Player
    description: Plays music
    commands: ["on", "off", play, pause, stop, displaymessage]
  squeezeboxserver:
    name: Squeezebox Server
    description: Squeezebox player manager
    commands: ["allon", "alloff", displaymessage]
  settopbox:
    name: Set top box
    description: Receives TV Service
    commands: ["on", "off", mute, unmute, mutetoggle, vol+, vol-, setlevel, setchannel, getepg]
  ipx800controller:
    name: IPX800 board controller
    description: Internal device to control IPX800 boards
    commands: [addipx800]
  ipx800board:
    name: IPX800
    description: Ethernet relay board
    commands: [addswitch, addshutter, addanalog, addcounter, allopen, allclose]
  ipx800switch:
    name: IPX800 switch
    description: Control single relay on IPX800
    commands: ["on", "off", forcestate]
  ipx800shutter:
    name: IPX800 shutter
    description: Control 2 relays on IPX800
    commands: [open, close, forcestate]
  ipx800analog:
    name: IPX800 analog
    description: Get value of analog input
    commands: []
  ipx800counter:
    name: IPX800 counter
    description: Get value of board counter
    commands: [resetcounter]
  alertcontroller:
    name: alert controller
    description: internal device to control the alerts
    commands: [twitterauthorizationurl, twitteraccesscode]
values:
  level:
    name: level
    description: level value
  channel:
    name: channel
    description: channel number
  devicetype:
    name: device type
    description: device type
  uuid:
    name: uuid
    description: unique id
  product:
    name: product
    description: product
  manufacturer:
    name: manufacturer
    description: manufacturer
  unit:
    name: unit
    description: unit of a value
  internalid:
    name: internal id for a device
    description: internal id used by interface device
  handled-by:
    name: instance name
    descroption: instance which handles the device
  minute:
    name: minute
    description: minute
  hour:
    name: hour
    description: hour
  second:
    name: second
    description: second
  month:
    name: month
    description: month
  day:
    name: day
    description: day
  year:
    name: year
    description: year
  weekday:
    name: weekday
    description: day of week
  yday:
    name: yday
    description: nth day of year
  callerid:
    name: caller identity
    description: the identity of a caller
  extension:
    name: phone extension
    description: extension being called
events:
  event.telecom.call:
    description: a call is originating
    parameters: [uuid, callerid, extension]
  event.telecom.hangup:
    description: call hung up
    parameters: [uuid]
  event.device.announce:
    description: announces a device to the resolver
    parameters: [devicetype, uuid, product, internal-id]
  event.device.statechanged:
    description: announces a status change of a device
    parameters: [level, uuid]
  event.environment.counterchanged:
    description: counter has changed
    parameters: [level, uuid]
  event.environment.temperaturechanged:
    description: temperature has changed
    parameters: [level, unit, uuid]
  event.environment.brightnesschanged:
    description: brightness has changed
    parameters: [level, unit, uuid]
  event.environment.humiditychanged:
    description: humidity has changed
    parameters: [level, unit, uuid]
  event.security.sensortriggered:
    description: sensor was triggererd
    parameters: [level, uuid]
  event.environment.sunset:
    description: sun has set
  event.environment.sunrise:
    description: sun did rise
  event.environment.timechanged:
    description: time did advance
    parameters: [minute, hour, month, day, year, weekday, yday]
  event.mediaplayer.statechanged:
    description: mediaplayer changed play state
    parameters: [new_state]
  event.security.intruderalert:
    description: intruder alarm
    parameters: [uuid]
  event.environment.energychanged:
    description: energy has changed
    parameters: [level, uuid]
units:
  degC:
    label: "°C"
    description: degree celcius
  percent:
    label: "%"
    description: percent value
