#!/bin/bash
# agocontrol-zwave postinst script
mkdir -p /etc/opt/agocontrol/ozw
chown -R agocontrol:agocontrol /etc/opt/agocontrol/ozw

test -e /etc/opt/agocontrol/uuidmap/zwave.json || (
	ZWCFGFILE=$(ls -tr /etc/opt/agocontrol/ozw/zwcfg_0x*.xml 2>>/dev/null| tail -1)
	if [ "$ZWCFGFILE" != "" ]; then
		echo migrating zwave uuids for new driver
		/opt/agocontrol/bin/convert-zwave-uuid.py ${ZWCFGFILE}
		chown agocontrol:agocontrol /etc/opt/agocontrol/uuidmap/zwave.json
	fi
)
