#!/bin/bash
# agocontrol postinst script
PASSWD=letmein

if ! getent passwd agocontrol > /dev/null ; then
    echo 'Adding system-user for agocontrol' 1>&2
    adduser --system --home /var/run/agocontrol --group --disabled-password agocontrol
    adduser agocontrol dialout
    mkdir -p /var/run/agocontrol
    chown agocontrol:agocontrol /var/run/agocontrol
fi

# replace config.ini if there is an old version without username setting
# grep -q username /etc/opt/agocontrol/config.ini || rm /etc/opt/agocontrol/config.ini

test -e /etc/opt/agocontrol/config.ini || (
	UUID=$(uuidgen)
	cat /etc/opt/agocontrol/config.ini.tpl | sed "s/<uuid>/${UUID}/" > /etc/opt/agocontrol/config.ini
)

test -e /etc/opt/agocontrol/inventory.db || (
	sqlite3 -init /etc/opt/agocontrol/inventory.sql /etc/opt/agocontrol/inventory.db .quit | tee
)

sasldblistusers2 -f /etc/qpid/qpidd.sasldb  | grep -q agocontrol || (
	echo $PASSWD | saslpasswd2 -c -p -f /etc/qpid/qpidd.sasldb -u QPID agocontrol
)

grep -q agocontrol /etc/qpid/qpidd.acl || sed -i 's/admin@QPID/admin@QPID agocontrol@QPID/g' /etc/qpid/qpidd.acl
chown .qpidd /etc/qpid/qpidd.acl

test -e /etc/opt/agocontrol/scenariomap.json || (
	test -e /etc/opt/agocontrol/scenarios.pck && (
		echo converting scenariomap
		/opt/agocontrol/bin/convert-scenario.py
		mv /etc/opt/agocontrol/scenarios.pck /etc/opt/agocontrol/scenarios.pck.obsolete
	)
)

chown -R agocontrol:agocontrol /etc/opt/agocontrol

# install datalogger 
if [ ! -d "/var/opt/agocontrol" ]; then
   mkdir -p /var/opt/agocontrol
fi

test -e /var/opt/agocontrol/datalogger.db || (
	sqlite3 -init /etc/opt/agocontrol/datalogger.sql /var/opt/agocontrol/datalogger.db .quit | tee
)

chown -R agocontrol:agocontrol /var/opt/agocontrol


