#!/bin/bash
# agocontrol postinst script
PASSWD=letmein

if ! getent passwd agocontrol > /dev/null ; then
    echo 'Adding system-user for agocontrol' 1>&2
    adduser --system --home /var/run/agocontrol --group --disabled-password agocontrol
    adduser agocontrol dialout
    mkdir -p /var/run/agocontrol
    chown agocontrol:agocontrol /var/run/agocontrol
fi


grep "00000000-0000-0000-000000000000" /etc/opt/agocontrol/conf.d/system.conf && (
	UUID=$(uuidgen)
	sed -i "s/00000000-0000-0000-000000000000/${UUID}/" /etc/opt/agocontrol/conf.d/system.conf
)

test -e /etc/opt/agocontrol/db/inventory.db || (
	test -e /etc/opt/agocontrol/inventory.db && (mv /etc/opt/agocontrol/inventory.db /etc/opt/agocontrol/db/inventory.db) || (
		sqlite3 -init /var/opt/agocontrol/inventory.sql /etc/opt/agocontrol/db/inventory.db .quit | tee
	)
)

sasldblistusers2 -f /etc/qpid/qpidd.sasldb  | grep -q agocontrol || (
	echo $PASSWD | saslpasswd2 -c -p -f /etc/qpid/qpidd.sasldb -u QPID agocontrol
)

grep -q agocontrol /etc/qpid/qpidd.acl || sed -i 's/admin@QPID/admin@QPID agocontrol@QPID/g' /etc/qpid/qpidd.acl
chown .qpidd /etc/qpid/qpidd.acl

test -e /etc/opt/agocontrol/scenariomap.json || (
	test -e /etc/opt/agocontrol/scenarios.pck && (
		echo converting scenariomap
		/opt/agocontrol/bin/convert-scenario.py
		mv /etc/opt/agocontrol/scenarios.pck /etc/opt/agocontrol/old/scenarios.pck.obsolete
	)
)
test -e /etc/opt/agocontrol/eventmap.json || (
	test -e /etc/opt/agocontrol/events.pck && (
		echo converting eventmap
		/opt/agocontrol/bin/convert-event.py
		mv /etc/opt/agocontrol/events.pck /etc/opt/agocontrol/old/events.pck.obsolete
	)
)

chown -R agocontrol:agocontrol /etc/opt/agocontrol

# install datalogger 
if [ ! -d "/var/opt/agocontrol" ]; then
   mkdir -p /var/opt/agocontrol
fi

test -e /var/opt/agocontrol/datalogger.db || (
	sqlite3 -init /var/opt/agocontrol/datalogger.sql /var/opt/agocontrol/datalogger.db .quit | tee
)

chown -R agocontrol:agocontrol /var/opt/agocontrol


