all:

install:
	$(INSTALL_DIR) $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) agojointspace.py $(DESTDIR)$(BINDIR)
	$(INSTALL_DIR) $(DESTDIR)$(CONFDIR)
	$(INSTALL_DIR) $(DESTDIR)$(CONFDIR)/jointspace


clean:
