all:

install:
	$(INSTALL_DIR) $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) agowake_on_lan.py $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) pinger.py $(DESTDIR)$(BINDIR)
	$(INSTALL_PROGRAM) configobj.py $(DESTDIR)$(BINDIR)

clean:
