/* soapActionEngineBindingProxy.cpp
   Generated by gSOAP 2.8.15 from ./onvif/onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapActionEngineBindingProxy.h"

ActionEngineBindingProxy::ActionEngineBindingProxy()
{	ActionEngineBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ActionEngineBindingProxy::ActionEngineBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

ActionEngineBindingProxy::ActionEngineBindingProxy(const char *url)
{	ActionEngineBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

ActionEngineBindingProxy::ActionEngineBindingProxy(soap_mode iomode)
{	ActionEngineBindingProxy_init(iomode, iomode);
}

ActionEngineBindingProxy::ActionEngineBindingProxy(const char *url, soap_mode iomode)
{	ActionEngineBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

ActionEngineBindingProxy::ActionEngineBindingProxy(soap_mode imode, soap_mode omode)
{	ActionEngineBindingProxy_init(imode, omode);
}

ActionEngineBindingProxy::~ActionEngineBindingProxy()
{ }

void ActionEngineBindingProxy::ActionEngineBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
	{"wsdd", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
	{"wsc", "http://schemas.xmlsoap.org/ws/2005/02/sc", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"ns4", "http://www.onvif.org/ver10/pacs", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"ns1", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
	{"ns2", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
	{"ns3", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
	{"ns5", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
	{"tad", "http://www.onvif.org/ver10/analyticsdevice/wsdl", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"tdn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
	{"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
	{"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
	{"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void ActionEngineBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void ActionEngineBindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	ActionEngineBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ActionEngineBindingProxy::soap_noheader()
{	this->header = NULL;
}

void ActionEngineBindingProxy::soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security)
{	::soap_header(this);
	this->header->wsa__MessageID = wsa__MessageID;
	this->header->wsa__RelatesTo = wsa__RelatesTo;
	this->header->wsa__From = wsa__From;
	this->header->wsa__ReplyTo = wsa__ReplyTo;
	this->header->wsa__FaultTo = wsa__FaultTo;
	this->header->wsa__To = wsa__To;
	this->header->wsa__Action = wsa__Action;
	this->header->wsdd__AppSequence = wsdd__AppSequence;
	this->header->wsa5__MessageID = wsa5__MessageID;
	this->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->header->wsa5__From = wsa5__From;
	this->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->header->wsa5__FaultTo = wsa5__FaultTo;
	this->header->wsa5__To = wsa5__To;
	this->header->wsa5__Action = wsa5__Action;
	this->header->chan__ChannelInstance = chan__ChannelInstance;
	this->header->wsse__Security = wsse__Security;
}

const SOAP_ENV__Header *ActionEngineBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *ActionEngineBindingProxy::soap_fault()
{	return this->fault;
}

const char *ActionEngineBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *ActionEngineBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int ActionEngineBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int ActionEngineBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void ActionEngineBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ActionEngineBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *ActionEngineBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int ActionEngineBindingProxy::GetSupportedActions(const char *endpoint, const char *soap_action, _ns2__GetSupportedActions *ns2__GetSupportedActions, _ns2__GetSupportedActionsResponse *ns2__GetSupportedActionsResponse)
{	struct soap *soap = this;
	struct __ns2__GetSupportedActions soap_tmp___ns2__GetSupportedActions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/GetSupportedActions";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetSupportedActions.ns2__GetSupportedActions = ns2__GetSupportedActions;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__GetSupportedActions(soap, &soap_tmp___ns2__GetSupportedActions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetSupportedActions(soap, &soap_tmp___ns2__GetSupportedActions, "-ns2:GetSupportedActions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetSupportedActions(soap, &soap_tmp___ns2__GetSupportedActions, "-ns2:GetSupportedActions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetSupportedActionsResponse)
		return soap_closesock(soap);
	ns2__GetSupportedActionsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetSupportedActionsResponse->soap_get(soap, "ns2:GetSupportedActionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::GetActions(const char *endpoint, const char *soap_action, _ns2__GetActions *ns2__GetActions, _ns2__GetActionsResponse *ns2__GetActionsResponse)
{	struct soap *soap = this;
	struct __ns2__GetActions soap_tmp___ns2__GetActions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/GetActions";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetActions.ns2__GetActions = ns2__GetActions;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__GetActions(soap, &soap_tmp___ns2__GetActions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetActions(soap, &soap_tmp___ns2__GetActions, "-ns2:GetActions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetActions(soap, &soap_tmp___ns2__GetActions, "-ns2:GetActions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetActionsResponse)
		return soap_closesock(soap);
	ns2__GetActionsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetActionsResponse->soap_get(soap, "ns2:GetActionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::CreateActions(const char *endpoint, const char *soap_action, _ns2__CreateActions *ns2__CreateActions, _ns2__CreateActionsResponse *ns2__CreateActionsResponse)
{	struct soap *soap = this;
	struct __ns2__CreateActions soap_tmp___ns2__CreateActions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/CreateActions";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CreateActions.ns2__CreateActions = ns2__CreateActions;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__CreateActions(soap, &soap_tmp___ns2__CreateActions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CreateActions(soap, &soap_tmp___ns2__CreateActions, "-ns2:CreateActions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CreateActions(soap, &soap_tmp___ns2__CreateActions, "-ns2:CreateActions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__CreateActionsResponse)
		return soap_closesock(soap);
	ns2__CreateActionsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__CreateActionsResponse->soap_get(soap, "ns2:CreateActionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::DeleteActions(const char *endpoint, const char *soap_action, _ns2__DeleteActions *ns2__DeleteActions, _ns2__DeleteActionsResponse *ns2__DeleteActionsResponse)
{	struct soap *soap = this;
	struct __ns2__DeleteActions soap_tmp___ns2__DeleteActions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/DeleteActions";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__DeleteActions.ns2__DeleteActions = ns2__DeleteActions;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__DeleteActions(soap, &soap_tmp___ns2__DeleteActions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__DeleteActions(soap, &soap_tmp___ns2__DeleteActions, "-ns2:DeleteActions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__DeleteActions(soap, &soap_tmp___ns2__DeleteActions, "-ns2:DeleteActions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__DeleteActionsResponse)
		return soap_closesock(soap);
	ns2__DeleteActionsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__DeleteActionsResponse->soap_get(soap, "ns2:DeleteActionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::ModifyActions(const char *endpoint, const char *soap_action, _ns2__ModifyActions *ns2__ModifyActions, _ns2__ModifyActionsResponse *ns2__ModifyActionsResponse)
{	struct soap *soap = this;
	struct __ns2__ModifyActions soap_tmp___ns2__ModifyActions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/ModifyActions";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__ModifyActions.ns2__ModifyActions = ns2__ModifyActions;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__ModifyActions(soap, &soap_tmp___ns2__ModifyActions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__ModifyActions(soap, &soap_tmp___ns2__ModifyActions, "-ns2:ModifyActions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__ModifyActions(soap, &soap_tmp___ns2__ModifyActions, "-ns2:ModifyActions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__ModifyActionsResponse)
		return soap_closesock(soap);
	ns2__ModifyActionsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__ModifyActionsResponse->soap_get(soap, "ns2:ModifyActionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns2__GetServiceCapabilities *ns2__GetServiceCapabilities, _ns2__GetServiceCapabilitiesResponse *ns2__GetServiceCapabilitiesResponse)
{	struct soap *soap = this;
	struct __ns2__GetServiceCapabilities soap_tmp___ns2__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/GetServiceCapabilities";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetServiceCapabilities.ns2__GetServiceCapabilities = ns2__GetServiceCapabilities;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__GetServiceCapabilities(soap, &soap_tmp___ns2__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetServiceCapabilities(soap, &soap_tmp___ns2__GetServiceCapabilities, "-ns2:GetServiceCapabilities", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetServiceCapabilities(soap, &soap_tmp___ns2__GetServiceCapabilities, "-ns2:GetServiceCapabilities", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetServiceCapabilitiesResponse)
		return soap_closesock(soap);
	ns2__GetServiceCapabilitiesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetServiceCapabilitiesResponse->soap_get(soap, "ns2:GetServiceCapabilitiesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::GetActionTriggers(const char *endpoint, const char *soap_action, _ns2__GetActionTriggers *ns2__GetActionTriggers, _ns2__GetActionTriggersResponse *ns2__GetActionTriggersResponse)
{	struct soap *soap = this;
	struct __ns2__GetActionTriggers soap_tmp___ns2__GetActionTriggers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/GetActionTriggers";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetActionTriggers.ns2__GetActionTriggers = ns2__GetActionTriggers;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__GetActionTriggers(soap, &soap_tmp___ns2__GetActionTriggers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetActionTriggers(soap, &soap_tmp___ns2__GetActionTriggers, "-ns2:GetActionTriggers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetActionTriggers(soap, &soap_tmp___ns2__GetActionTriggers, "-ns2:GetActionTriggers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetActionTriggersResponse)
		return soap_closesock(soap);
	ns2__GetActionTriggersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetActionTriggersResponse->soap_get(soap, "ns2:GetActionTriggersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::CreateActionTriggers(const char *endpoint, const char *soap_action, _ns2__CreateActionTriggers *ns2__CreateActionTriggers, _ns2__CreateActionTriggersResponse *ns2__CreateActionTriggersResponse)
{	struct soap *soap = this;
	struct __ns2__CreateActionTriggers soap_tmp___ns2__CreateActionTriggers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/CreateActionTriggers";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CreateActionTriggers.ns2__CreateActionTriggers = ns2__CreateActionTriggers;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__CreateActionTriggers(soap, &soap_tmp___ns2__CreateActionTriggers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CreateActionTriggers(soap, &soap_tmp___ns2__CreateActionTriggers, "-ns2:CreateActionTriggers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CreateActionTriggers(soap, &soap_tmp___ns2__CreateActionTriggers, "-ns2:CreateActionTriggers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__CreateActionTriggersResponse)
		return soap_closesock(soap);
	ns2__CreateActionTriggersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__CreateActionTriggersResponse->soap_get(soap, "ns2:CreateActionTriggersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::DeleteActionTriggers(const char *endpoint, const char *soap_action, _ns2__DeleteActionTriggers *ns2__DeleteActionTriggers, _ns2__DeleteActionTriggersResponse *ns2__DeleteActionTriggersResponse)
{	struct soap *soap = this;
	struct __ns2__DeleteActionTriggers soap_tmp___ns2__DeleteActionTriggers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/DeleteActionTriggers";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__DeleteActionTriggers.ns2__DeleteActionTriggers = ns2__DeleteActionTriggers;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__DeleteActionTriggers(soap, &soap_tmp___ns2__DeleteActionTriggers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__DeleteActionTriggers(soap, &soap_tmp___ns2__DeleteActionTriggers, "-ns2:DeleteActionTriggers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__DeleteActionTriggers(soap, &soap_tmp___ns2__DeleteActionTriggers, "-ns2:DeleteActionTriggers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__DeleteActionTriggersResponse)
		return soap_closesock(soap);
	ns2__DeleteActionTriggersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__DeleteActionTriggersResponse->soap_get(soap, "ns2:DeleteActionTriggersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ActionEngineBindingProxy::ModifyActionTriggers(const char *endpoint, const char *soap_action, _ns2__ModifyActionTriggers *ns2__ModifyActionTriggers, _ns2__ModifyActionTriggersResponse *ns2__ModifyActionTriggersResponse)
{	struct soap *soap = this;
	struct __ns2__ModifyActionTriggers soap_tmp___ns2__ModifyActionTriggers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/actionengine/wsdl/ModifyActionTriggers";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__ModifyActionTriggers.ns2__ModifyActionTriggers = ns2__ModifyActionTriggers;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns2__ModifyActionTriggers(soap, &soap_tmp___ns2__ModifyActionTriggers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__ModifyActionTriggers(soap, &soap_tmp___ns2__ModifyActionTriggers, "-ns2:ModifyActionTriggers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__ModifyActionTriggers(soap, &soap_tmp___ns2__ModifyActionTriggers, "-ns2:ModifyActionTriggers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__ModifyActionTriggersResponse)
		return soap_closesock(soap);
	ns2__ModifyActionTriggersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__ModifyActionTriggersResponse->soap_get(soap, "ns2:ModifyActionTriggersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
