/* soapDoorControlBindingProxy.h
   Generated by gSOAP 2.8.15 from ./onvif/onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapDoorControlBindingProxy_H
#define soapDoorControlBindingProxy_H
#include "soapH.h"

class SOAP_CMAC DoorControlBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'DoorControlBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	DoorControlBindingProxy();
	/// Construct from another engine state
	DoorControlBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	DoorControlBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	DoorControlBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	DoorControlBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	DoorControlBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~DoorControlBindingProxy();
	/// Initializer used by constructors
	virtual	void DoorControlBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities(_ns5__GetServiceCapabilities *ns5__GetServiceCapabilities, _ns5__GetServiceCapabilitiesResponse *ns5__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, ns5__GetServiceCapabilities, ns5__GetServiceCapabilitiesResponse); }
	virtual	int GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns5__GetServiceCapabilities *ns5__GetServiceCapabilities, _ns5__GetServiceCapabilitiesResponse *ns5__GetServiceCapabilitiesResponse);

	/// Web service operation 'GetDoorInfoList' (returns error code or SOAP_OK)
	virtual	int GetDoorInfoList(_ns5__GetDoorInfoList *ns5__GetDoorInfoList, _ns5__GetDoorInfoListResponse *ns5__GetDoorInfoListResponse) { return this->GetDoorInfoList(NULL, NULL, ns5__GetDoorInfoList, ns5__GetDoorInfoListResponse); }
	virtual	int GetDoorInfoList(const char *endpoint, const char *soap_action, _ns5__GetDoorInfoList *ns5__GetDoorInfoList, _ns5__GetDoorInfoListResponse *ns5__GetDoorInfoListResponse);

	/// Web service operation 'GetDoorInfo' (returns error code or SOAP_OK)
	virtual	int GetDoorInfo(_ns5__GetDoorInfo *ns5__GetDoorInfo, _ns5__GetDoorInfoResponse *ns5__GetDoorInfoResponse) { return this->GetDoorInfo(NULL, NULL, ns5__GetDoorInfo, ns5__GetDoorInfoResponse); }
	virtual	int GetDoorInfo(const char *endpoint, const char *soap_action, _ns5__GetDoorInfo *ns5__GetDoorInfo, _ns5__GetDoorInfoResponse *ns5__GetDoorInfoResponse);

	/// Web service operation 'GetDoorState' (returns error code or SOAP_OK)
	virtual	int GetDoorState(_ns5__GetDoorState *ns5__GetDoorState, _ns5__GetDoorStateResponse *ns5__GetDoorStateResponse) { return this->GetDoorState(NULL, NULL, ns5__GetDoorState, ns5__GetDoorStateResponse); }
	virtual	int GetDoorState(const char *endpoint, const char *soap_action, _ns5__GetDoorState *ns5__GetDoorState, _ns5__GetDoorStateResponse *ns5__GetDoorStateResponse);

	/// Web service operation 'AccessDoor' (returns error code or SOAP_OK)
	virtual	int AccessDoor(_ns5__AccessDoor *ns5__AccessDoor, _ns5__AccessDoorResponse *ns5__AccessDoorResponse) { return this->AccessDoor(NULL, NULL, ns5__AccessDoor, ns5__AccessDoorResponse); }
	virtual	int AccessDoor(const char *endpoint, const char *soap_action, _ns5__AccessDoor *ns5__AccessDoor, _ns5__AccessDoorResponse *ns5__AccessDoorResponse);

	/// Web service operation 'LockDoor' (returns error code or SOAP_OK)
	virtual	int LockDoor(_ns5__LockDoor *ns5__LockDoor, _ns5__LockDoorResponse *ns5__LockDoorResponse) { return this->LockDoor(NULL, NULL, ns5__LockDoor, ns5__LockDoorResponse); }
	virtual	int LockDoor(const char *endpoint, const char *soap_action, _ns5__LockDoor *ns5__LockDoor, _ns5__LockDoorResponse *ns5__LockDoorResponse);

	/// Web service operation 'UnlockDoor' (returns error code or SOAP_OK)
	virtual	int UnlockDoor(_ns5__UnlockDoor *ns5__UnlockDoor, _ns5__UnlockDoorResponse *ns5__UnlockDoorResponse) { return this->UnlockDoor(NULL, NULL, ns5__UnlockDoor, ns5__UnlockDoorResponse); }
	virtual	int UnlockDoor(const char *endpoint, const char *soap_action, _ns5__UnlockDoor *ns5__UnlockDoor, _ns5__UnlockDoorResponse *ns5__UnlockDoorResponse);

	/// Web service operation 'BlockDoor' (returns error code or SOAP_OK)
	virtual	int BlockDoor(_ns5__BlockDoor *ns5__BlockDoor, _ns5__BlockDoorResponse *ns5__BlockDoorResponse) { return this->BlockDoor(NULL, NULL, ns5__BlockDoor, ns5__BlockDoorResponse); }
	virtual	int BlockDoor(const char *endpoint, const char *soap_action, _ns5__BlockDoor *ns5__BlockDoor, _ns5__BlockDoorResponse *ns5__BlockDoorResponse);

	/// Web service operation 'LockDownDoor' (returns error code or SOAP_OK)
	virtual	int LockDownDoor(_ns5__LockDownDoor *ns5__LockDownDoor, _ns5__LockDownDoorResponse *ns5__LockDownDoorResponse) { return this->LockDownDoor(NULL, NULL, ns5__LockDownDoor, ns5__LockDownDoorResponse); }
	virtual	int LockDownDoor(const char *endpoint, const char *soap_action, _ns5__LockDownDoor *ns5__LockDownDoor, _ns5__LockDownDoorResponse *ns5__LockDownDoorResponse);

	/// Web service operation 'LockDownReleaseDoor' (returns error code or SOAP_OK)
	virtual	int LockDownReleaseDoor(_ns5__LockDownReleaseDoor *ns5__LockDownReleaseDoor, _ns5__LockDownReleaseDoorResponse *ns5__LockDownReleaseDoorResponse) { return this->LockDownReleaseDoor(NULL, NULL, ns5__LockDownReleaseDoor, ns5__LockDownReleaseDoorResponse); }
	virtual	int LockDownReleaseDoor(const char *endpoint, const char *soap_action, _ns5__LockDownReleaseDoor *ns5__LockDownReleaseDoor, _ns5__LockDownReleaseDoorResponse *ns5__LockDownReleaseDoorResponse);

	/// Web service operation 'LockOpenDoor' (returns error code or SOAP_OK)
	virtual	int LockOpenDoor(_ns5__LockOpenDoor *ns5__LockOpenDoor, _ns5__LockOpenDoorResponse *ns5__LockOpenDoorResponse) { return this->LockOpenDoor(NULL, NULL, ns5__LockOpenDoor, ns5__LockOpenDoorResponse); }
	virtual	int LockOpenDoor(const char *endpoint, const char *soap_action, _ns5__LockOpenDoor *ns5__LockOpenDoor, _ns5__LockOpenDoorResponse *ns5__LockOpenDoorResponse);

	/// Web service operation 'LockOpenReleaseDoor' (returns error code or SOAP_OK)
	virtual	int LockOpenReleaseDoor(_ns5__LockOpenReleaseDoor *ns5__LockOpenReleaseDoor, _ns5__LockOpenReleaseDoorResponse *ns5__LockOpenReleaseDoorResponse) { return this->LockOpenReleaseDoor(NULL, NULL, ns5__LockOpenReleaseDoor, ns5__LockOpenReleaseDoorResponse); }
	virtual	int LockOpenReleaseDoor(const char *endpoint, const char *soap_action, _ns5__LockOpenReleaseDoor *ns5__LockOpenReleaseDoor, _ns5__LockOpenReleaseDoorResponse *ns5__LockOpenReleaseDoorResponse);

	/// Web service operation 'DoubleLockDoor' (returns error code or SOAP_OK)
	virtual	int DoubleLockDoor(_ns5__DoubleLockDoor *ns5__DoubleLockDoor, _ns5__DoubleLockDoorResponse *ns5__DoubleLockDoorResponse) { return this->DoubleLockDoor(NULL, NULL, ns5__DoubleLockDoor, ns5__DoubleLockDoorResponse); }
	virtual	int DoubleLockDoor(const char *endpoint, const char *soap_action, _ns5__DoubleLockDoor *ns5__DoubleLockDoor, _ns5__DoubleLockDoorResponse *ns5__DoubleLockDoorResponse);
};
#endif
