/* soapActionEngineBindingProxy.h
   Generated by gSOAP 2.8.15 from ./onvif/onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapActionEngineBindingProxy_H
#define soapActionEngineBindingProxy_H
#include "soapH.h"

class SOAP_CMAC ActionEngineBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'ActionEngineBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ActionEngineBindingProxy();
	/// Construct from another engine state
	ActionEngineBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	ActionEngineBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	ActionEngineBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ActionEngineBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ActionEngineBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ActionEngineBindingProxy();
	/// Initializer used by constructors
	virtual	void ActionEngineBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetSupportedActions' (returns error code or SOAP_OK)
	virtual	int GetSupportedActions(_ns2__GetSupportedActions *ns2__GetSupportedActions, _ns2__GetSupportedActionsResponse *ns2__GetSupportedActionsResponse) { return this->GetSupportedActions(NULL, NULL, ns2__GetSupportedActions, ns2__GetSupportedActionsResponse); }
	virtual	int GetSupportedActions(const char *endpoint, const char *soap_action, _ns2__GetSupportedActions *ns2__GetSupportedActions, _ns2__GetSupportedActionsResponse *ns2__GetSupportedActionsResponse);

	/// Web service operation 'GetActions' (returns error code or SOAP_OK)
	virtual	int GetActions(_ns2__GetActions *ns2__GetActions, _ns2__GetActionsResponse *ns2__GetActionsResponse) { return this->GetActions(NULL, NULL, ns2__GetActions, ns2__GetActionsResponse); }
	virtual	int GetActions(const char *endpoint, const char *soap_action, _ns2__GetActions *ns2__GetActions, _ns2__GetActionsResponse *ns2__GetActionsResponse);

	/// Web service operation 'CreateActions' (returns error code or SOAP_OK)
	virtual	int CreateActions(_ns2__CreateActions *ns2__CreateActions, _ns2__CreateActionsResponse *ns2__CreateActionsResponse) { return this->CreateActions(NULL, NULL, ns2__CreateActions, ns2__CreateActionsResponse); }
	virtual	int CreateActions(const char *endpoint, const char *soap_action, _ns2__CreateActions *ns2__CreateActions, _ns2__CreateActionsResponse *ns2__CreateActionsResponse);

	/// Web service operation 'DeleteActions' (returns error code or SOAP_OK)
	virtual	int DeleteActions(_ns2__DeleteActions *ns2__DeleteActions, _ns2__DeleteActionsResponse *ns2__DeleteActionsResponse) { return this->DeleteActions(NULL, NULL, ns2__DeleteActions, ns2__DeleteActionsResponse); }
	virtual	int DeleteActions(const char *endpoint, const char *soap_action, _ns2__DeleteActions *ns2__DeleteActions, _ns2__DeleteActionsResponse *ns2__DeleteActionsResponse);

	/// Web service operation 'ModifyActions' (returns error code or SOAP_OK)
	virtual	int ModifyActions(_ns2__ModifyActions *ns2__ModifyActions, _ns2__ModifyActionsResponse *ns2__ModifyActionsResponse) { return this->ModifyActions(NULL, NULL, ns2__ModifyActions, ns2__ModifyActionsResponse); }
	virtual	int ModifyActions(const char *endpoint, const char *soap_action, _ns2__ModifyActions *ns2__ModifyActions, _ns2__ModifyActionsResponse *ns2__ModifyActionsResponse);

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities(_ns2__GetServiceCapabilities *ns2__GetServiceCapabilities, _ns2__GetServiceCapabilitiesResponse *ns2__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, ns2__GetServiceCapabilities, ns2__GetServiceCapabilitiesResponse); }
	virtual	int GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns2__GetServiceCapabilities *ns2__GetServiceCapabilities, _ns2__GetServiceCapabilitiesResponse *ns2__GetServiceCapabilitiesResponse);

	/// Web service operation 'GetActionTriggers' (returns error code or SOAP_OK)
	virtual	int GetActionTriggers(_ns2__GetActionTriggers *ns2__GetActionTriggers, _ns2__GetActionTriggersResponse *ns2__GetActionTriggersResponse) { return this->GetActionTriggers(NULL, NULL, ns2__GetActionTriggers, ns2__GetActionTriggersResponse); }
	virtual	int GetActionTriggers(const char *endpoint, const char *soap_action, _ns2__GetActionTriggers *ns2__GetActionTriggers, _ns2__GetActionTriggersResponse *ns2__GetActionTriggersResponse);

	/// Web service operation 'CreateActionTriggers' (returns error code or SOAP_OK)
	virtual	int CreateActionTriggers(_ns2__CreateActionTriggers *ns2__CreateActionTriggers, _ns2__CreateActionTriggersResponse *ns2__CreateActionTriggersResponse) { return this->CreateActionTriggers(NULL, NULL, ns2__CreateActionTriggers, ns2__CreateActionTriggersResponse); }
	virtual	int CreateActionTriggers(const char *endpoint, const char *soap_action, _ns2__CreateActionTriggers *ns2__CreateActionTriggers, _ns2__CreateActionTriggersResponse *ns2__CreateActionTriggersResponse);

	/// Web service operation 'DeleteActionTriggers' (returns error code or SOAP_OK)
	virtual	int DeleteActionTriggers(_ns2__DeleteActionTriggers *ns2__DeleteActionTriggers, _ns2__DeleteActionTriggersResponse *ns2__DeleteActionTriggersResponse) { return this->DeleteActionTriggers(NULL, NULL, ns2__DeleteActionTriggers, ns2__DeleteActionTriggersResponse); }
	virtual	int DeleteActionTriggers(const char *endpoint, const char *soap_action, _ns2__DeleteActionTriggers *ns2__DeleteActionTriggers, _ns2__DeleteActionTriggersResponse *ns2__DeleteActionTriggersResponse);

	/// Web service operation 'ModifyActionTriggers' (returns error code or SOAP_OK)
	virtual	int ModifyActionTriggers(_ns2__ModifyActionTriggers *ns2__ModifyActionTriggers, _ns2__ModifyActionTriggersResponse *ns2__ModifyActionTriggersResponse) { return this->ModifyActionTriggers(NULL, NULL, ns2__ModifyActionTriggers, ns2__ModifyActionTriggersResponse); }
	virtual	int ModifyActionTriggers(const char *endpoint, const char *soap_action, _ns2__ModifyActionTriggers *ns2__ModifyActionTriggers, _ns2__ModifyActionTriggersResponse *ns2__ModifyActionTriggersResponse);
};
#endif
