/* soapAnalyticsDeviceBindingProxy.cpp
   Generated by gSOAP 2.8.15 from ./onvif/onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapAnalyticsDeviceBindingProxy.h"

AnalyticsDeviceBindingProxy::AnalyticsDeviceBindingProxy()
{	AnalyticsDeviceBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

AnalyticsDeviceBindingProxy::AnalyticsDeviceBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

AnalyticsDeviceBindingProxy::AnalyticsDeviceBindingProxy(const char *url)
{	AnalyticsDeviceBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

AnalyticsDeviceBindingProxy::AnalyticsDeviceBindingProxy(soap_mode iomode)
{	AnalyticsDeviceBindingProxy_init(iomode, iomode);
}

AnalyticsDeviceBindingProxy::AnalyticsDeviceBindingProxy(const char *url, soap_mode iomode)
{	AnalyticsDeviceBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

AnalyticsDeviceBindingProxy::AnalyticsDeviceBindingProxy(soap_mode imode, soap_mode omode)
{	AnalyticsDeviceBindingProxy_init(imode, omode);
}

AnalyticsDeviceBindingProxy::~AnalyticsDeviceBindingProxy()
{ }

void AnalyticsDeviceBindingProxy::AnalyticsDeviceBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
	{"wsdd", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
	{"wsc", "http://schemas.xmlsoap.org/ws/2005/02/sc", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"ns4", "http://www.onvif.org/ver10/pacs", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"ns1", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
	{"ns2", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
	{"ns3", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
	{"ns5", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
	{"tad", "http://www.onvif.org/ver10/analyticsdevice/wsdl", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"tdn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
	{"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
	{"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
	{"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void AnalyticsDeviceBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void AnalyticsDeviceBindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	AnalyticsDeviceBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void AnalyticsDeviceBindingProxy::soap_noheader()
{	this->header = NULL;
}

void AnalyticsDeviceBindingProxy::soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security)
{	::soap_header(this);
	this->header->wsa__MessageID = wsa__MessageID;
	this->header->wsa__RelatesTo = wsa__RelatesTo;
	this->header->wsa__From = wsa__From;
	this->header->wsa__ReplyTo = wsa__ReplyTo;
	this->header->wsa__FaultTo = wsa__FaultTo;
	this->header->wsa__To = wsa__To;
	this->header->wsa__Action = wsa__Action;
	this->header->wsdd__AppSequence = wsdd__AppSequence;
	this->header->wsa5__MessageID = wsa5__MessageID;
	this->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->header->wsa5__From = wsa5__From;
	this->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->header->wsa5__FaultTo = wsa5__FaultTo;
	this->header->wsa5__To = wsa5__To;
	this->header->wsa5__Action = wsa5__Action;
	this->header->chan__ChannelInstance = chan__ChannelInstance;
	this->header->wsse__Security = wsse__Security;
}

const SOAP_ENV__Header *AnalyticsDeviceBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *AnalyticsDeviceBindingProxy::soap_fault()
{	return this->fault;
}

const char *AnalyticsDeviceBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *AnalyticsDeviceBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int AnalyticsDeviceBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int AnalyticsDeviceBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void AnalyticsDeviceBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void AnalyticsDeviceBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *AnalyticsDeviceBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int AnalyticsDeviceBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _tad__GetServiceCapabilities *tad__GetServiceCapabilities, _tad__GetServiceCapabilitiesResponse *tad__GetServiceCapabilitiesResponse)
{	struct soap *soap = this;
	struct __tad__GetServiceCapabilities soap_tmp___tad__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetServiceCapabilities";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetServiceCapabilities.tad__GetServiceCapabilities = tad__GetServiceCapabilities;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetServiceCapabilities(soap, &soap_tmp___tad__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetServiceCapabilities(soap, &soap_tmp___tad__GetServiceCapabilities, "-tad:GetServiceCapabilities", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetServiceCapabilities(soap, &soap_tmp___tad__GetServiceCapabilities, "-tad:GetServiceCapabilities", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetServiceCapabilitiesResponse)
		return soap_closesock(soap);
	tad__GetServiceCapabilitiesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetServiceCapabilitiesResponse->soap_get(soap, "tad:GetServiceCapabilitiesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::DeleteAnalyticsEngineControl(const char *endpoint, const char *soap_action, _tad__DeleteAnalyticsEngineControl *tad__DeleteAnalyticsEngineControl, _tad__DeleteAnalyticsEngineControlResponse *tad__DeleteAnalyticsEngineControlResponse)
{	struct soap *soap = this;
	struct __tad__DeleteAnalyticsEngineControl soap_tmp___tad__DeleteAnalyticsEngineControl;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/DeleteAnalyticsEngineControl";
	soap->encodingStyle = NULL;
	soap_tmp___tad__DeleteAnalyticsEngineControl.tad__DeleteAnalyticsEngineControl = tad__DeleteAnalyticsEngineControl;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__DeleteAnalyticsEngineControl(soap, &soap_tmp___tad__DeleteAnalyticsEngineControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__DeleteAnalyticsEngineControl(soap, &soap_tmp___tad__DeleteAnalyticsEngineControl, "-tad:DeleteAnalyticsEngineControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__DeleteAnalyticsEngineControl(soap, &soap_tmp___tad__DeleteAnalyticsEngineControl, "-tad:DeleteAnalyticsEngineControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__DeleteAnalyticsEngineControlResponse)
		return soap_closesock(soap);
	tad__DeleteAnalyticsEngineControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__DeleteAnalyticsEngineControlResponse->soap_get(soap, "tad:DeleteAnalyticsEngineControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::CreateAnalyticsEngineControl(const char *endpoint, const char *soap_action, _tad__CreateAnalyticsEngineControl *tad__CreateAnalyticsEngineControl, _tad__CreateAnalyticsEngineControlResponse *tad__CreateAnalyticsEngineControlResponse)
{	struct soap *soap = this;
	struct __tad__CreateAnalyticsEngineControl soap_tmp___tad__CreateAnalyticsEngineControl;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/CreateAnalyticsEngineControl";
	soap->encodingStyle = NULL;
	soap_tmp___tad__CreateAnalyticsEngineControl.tad__CreateAnalyticsEngineControl = tad__CreateAnalyticsEngineControl;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__CreateAnalyticsEngineControl(soap, &soap_tmp___tad__CreateAnalyticsEngineControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__CreateAnalyticsEngineControl(soap, &soap_tmp___tad__CreateAnalyticsEngineControl, "-tad:CreateAnalyticsEngineControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__CreateAnalyticsEngineControl(soap, &soap_tmp___tad__CreateAnalyticsEngineControl, "-tad:CreateAnalyticsEngineControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__CreateAnalyticsEngineControlResponse)
		return soap_closesock(soap);
	tad__CreateAnalyticsEngineControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__CreateAnalyticsEngineControlResponse->soap_get(soap, "tad:CreateAnalyticsEngineControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::SetAnalyticsEngineControl(const char *endpoint, const char *soap_action, _tad__SetAnalyticsEngineControl *tad__SetAnalyticsEngineControl, _tad__SetAnalyticsEngineControlResponse *tad__SetAnalyticsEngineControlResponse)
{	struct soap *soap = this;
	struct __tad__SetAnalyticsEngineControl soap_tmp___tad__SetAnalyticsEngineControl;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/SetAnalyticsEngineControl";
	soap->encodingStyle = NULL;
	soap_tmp___tad__SetAnalyticsEngineControl.tad__SetAnalyticsEngineControl = tad__SetAnalyticsEngineControl;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__SetAnalyticsEngineControl(soap, &soap_tmp___tad__SetAnalyticsEngineControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__SetAnalyticsEngineControl(soap, &soap_tmp___tad__SetAnalyticsEngineControl, "-tad:SetAnalyticsEngineControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__SetAnalyticsEngineControl(soap, &soap_tmp___tad__SetAnalyticsEngineControl, "-tad:SetAnalyticsEngineControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__SetAnalyticsEngineControlResponse)
		return soap_closesock(soap);
	tad__SetAnalyticsEngineControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__SetAnalyticsEngineControlResponse->soap_get(soap, "tad:SetAnalyticsEngineControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetAnalyticsEngineControl(const char *endpoint, const char *soap_action, _tad__GetAnalyticsEngineControl *tad__GetAnalyticsEngineControl, _tad__GetAnalyticsEngineControlResponse *tad__GetAnalyticsEngineControlResponse)
{	struct soap *soap = this;
	struct __tad__GetAnalyticsEngineControl soap_tmp___tad__GetAnalyticsEngineControl;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngineControl";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetAnalyticsEngineControl.tad__GetAnalyticsEngineControl = tad__GetAnalyticsEngineControl;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetAnalyticsEngineControl(soap, &soap_tmp___tad__GetAnalyticsEngineControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetAnalyticsEngineControl(soap, &soap_tmp___tad__GetAnalyticsEngineControl, "-tad:GetAnalyticsEngineControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetAnalyticsEngineControl(soap, &soap_tmp___tad__GetAnalyticsEngineControl, "-tad:GetAnalyticsEngineControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetAnalyticsEngineControlResponse)
		return soap_closesock(soap);
	tad__GetAnalyticsEngineControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetAnalyticsEngineControlResponse->soap_get(soap, "tad:GetAnalyticsEngineControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetAnalyticsEngineControls(const char *endpoint, const char *soap_action, _tad__GetAnalyticsEngineControls *tad__GetAnalyticsEngineControls, _tad__GetAnalyticsEngineControlsResponse *tad__GetAnalyticsEngineControlsResponse)
{	struct soap *soap = this;
	struct __tad__GetAnalyticsEngineControls soap_tmp___tad__GetAnalyticsEngineControls;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngineControls";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetAnalyticsEngineControls.tad__GetAnalyticsEngineControls = tad__GetAnalyticsEngineControls;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetAnalyticsEngineControls(soap, &soap_tmp___tad__GetAnalyticsEngineControls);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetAnalyticsEngineControls(soap, &soap_tmp___tad__GetAnalyticsEngineControls, "-tad:GetAnalyticsEngineControls", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetAnalyticsEngineControls(soap, &soap_tmp___tad__GetAnalyticsEngineControls, "-tad:GetAnalyticsEngineControls", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetAnalyticsEngineControlsResponse)
		return soap_closesock(soap);
	tad__GetAnalyticsEngineControlsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetAnalyticsEngineControlsResponse->soap_get(soap, "tad:GetAnalyticsEngineControlsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetAnalyticsEngine(const char *endpoint, const char *soap_action, _tad__GetAnalyticsEngine *tad__GetAnalyticsEngine, _tad__GetAnalyticsEngineResponse *tad__GetAnalyticsEngineResponse)
{	struct soap *soap = this;
	struct __tad__GetAnalyticsEngine soap_tmp___tad__GetAnalyticsEngine;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngine";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetAnalyticsEngine.tad__GetAnalyticsEngine = tad__GetAnalyticsEngine;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetAnalyticsEngine(soap, &soap_tmp___tad__GetAnalyticsEngine);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetAnalyticsEngine(soap, &soap_tmp___tad__GetAnalyticsEngine, "-tad:GetAnalyticsEngine", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetAnalyticsEngine(soap, &soap_tmp___tad__GetAnalyticsEngine, "-tad:GetAnalyticsEngine", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetAnalyticsEngineResponse)
		return soap_closesock(soap);
	tad__GetAnalyticsEngineResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetAnalyticsEngineResponse->soap_get(soap, "tad:GetAnalyticsEngineResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetAnalyticsEngines(const char *endpoint, const char *soap_action, _tad__GetAnalyticsEngines *tad__GetAnalyticsEngines, _tad__GetAnalyticsEnginesResponse *tad__GetAnalyticsEnginesResponse)
{	struct soap *soap = this;
	struct __tad__GetAnalyticsEngines soap_tmp___tad__GetAnalyticsEngines;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngines";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetAnalyticsEngines.tad__GetAnalyticsEngines = tad__GetAnalyticsEngines;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetAnalyticsEngines(soap, &soap_tmp___tad__GetAnalyticsEngines);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetAnalyticsEngines(soap, &soap_tmp___tad__GetAnalyticsEngines, "-tad:GetAnalyticsEngines", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetAnalyticsEngines(soap, &soap_tmp___tad__GetAnalyticsEngines, "-tad:GetAnalyticsEngines", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetAnalyticsEnginesResponse)
		return soap_closesock(soap);
	tad__GetAnalyticsEnginesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetAnalyticsEnginesResponse->soap_get(soap, "tad:GetAnalyticsEnginesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::SetVideoAnalyticsConfiguration(const char *endpoint, const char *soap_action, _tad__SetVideoAnalyticsConfiguration *tad__SetVideoAnalyticsConfiguration, _tad__SetVideoAnalyticsConfigurationResponse *tad__SetVideoAnalyticsConfigurationResponse)
{	struct soap *soap = this;
	struct __tad__SetVideoAnalyticsConfiguration soap_tmp___tad__SetVideoAnalyticsConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/SetVideoAnalyticsConfiguration";
	soap->encodingStyle = NULL;
	soap_tmp___tad__SetVideoAnalyticsConfiguration.tad__SetVideoAnalyticsConfiguration = tad__SetVideoAnalyticsConfiguration;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__SetVideoAnalyticsConfiguration(soap, &soap_tmp___tad__SetVideoAnalyticsConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__SetVideoAnalyticsConfiguration(soap, &soap_tmp___tad__SetVideoAnalyticsConfiguration, "-tad:SetVideoAnalyticsConfiguration", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__SetVideoAnalyticsConfiguration(soap, &soap_tmp___tad__SetVideoAnalyticsConfiguration, "-tad:SetVideoAnalyticsConfiguration", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__SetVideoAnalyticsConfigurationResponse)
		return soap_closesock(soap);
	tad__SetVideoAnalyticsConfigurationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__SetVideoAnalyticsConfigurationResponse->soap_get(soap, "tad:SetVideoAnalyticsConfigurationResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::SetAnalyticsEngineInput(const char *endpoint, const char *soap_action, _tad__SetAnalyticsEngineInput *tad__SetAnalyticsEngineInput, _tad__SetAnalyticsEngineInputResponse *tad__SetAnalyticsEngineInputResponse)
{	struct soap *soap = this;
	struct __tad__SetAnalyticsEngineInput soap_tmp___tad__SetAnalyticsEngineInput;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/SetAnalyticsEngineInput";
	soap->encodingStyle = NULL;
	soap_tmp___tad__SetAnalyticsEngineInput.tad__SetAnalyticsEngineInput = tad__SetAnalyticsEngineInput;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__SetAnalyticsEngineInput(soap, &soap_tmp___tad__SetAnalyticsEngineInput);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__SetAnalyticsEngineInput(soap, &soap_tmp___tad__SetAnalyticsEngineInput, "-tad:SetAnalyticsEngineInput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__SetAnalyticsEngineInput(soap, &soap_tmp___tad__SetAnalyticsEngineInput, "-tad:SetAnalyticsEngineInput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__SetAnalyticsEngineInputResponse)
		return soap_closesock(soap);
	tad__SetAnalyticsEngineInputResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__SetAnalyticsEngineInputResponse->soap_get(soap, "tad:SetAnalyticsEngineInputResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetAnalyticsEngineInput(const char *endpoint, const char *soap_action, _tad__GetAnalyticsEngineInput *tad__GetAnalyticsEngineInput, _tad__GetAnalyticsEngineInputResponse *tad__GetAnalyticsEngineInputResponse)
{	struct soap *soap = this;
	struct __tad__GetAnalyticsEngineInput soap_tmp___tad__GetAnalyticsEngineInput;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngineInput";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetAnalyticsEngineInput.tad__GetAnalyticsEngineInput = tad__GetAnalyticsEngineInput;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetAnalyticsEngineInput(soap, &soap_tmp___tad__GetAnalyticsEngineInput);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetAnalyticsEngineInput(soap, &soap_tmp___tad__GetAnalyticsEngineInput, "-tad:GetAnalyticsEngineInput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetAnalyticsEngineInput(soap, &soap_tmp___tad__GetAnalyticsEngineInput, "-tad:GetAnalyticsEngineInput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetAnalyticsEngineInputResponse)
		return soap_closesock(soap);
	tad__GetAnalyticsEngineInputResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetAnalyticsEngineInputResponse->soap_get(soap, "tad:GetAnalyticsEngineInputResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetAnalyticsEngineInputs(const char *endpoint, const char *soap_action, _tad__GetAnalyticsEngineInputs *tad__GetAnalyticsEngineInputs, _tad__GetAnalyticsEngineInputsResponse *tad__GetAnalyticsEngineInputsResponse)
{	struct soap *soap = this;
	struct __tad__GetAnalyticsEngineInputs soap_tmp___tad__GetAnalyticsEngineInputs;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngineInputs";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetAnalyticsEngineInputs.tad__GetAnalyticsEngineInputs = tad__GetAnalyticsEngineInputs;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetAnalyticsEngineInputs(soap, &soap_tmp___tad__GetAnalyticsEngineInputs);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetAnalyticsEngineInputs(soap, &soap_tmp___tad__GetAnalyticsEngineInputs, "-tad:GetAnalyticsEngineInputs", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetAnalyticsEngineInputs(soap, &soap_tmp___tad__GetAnalyticsEngineInputs, "-tad:GetAnalyticsEngineInputs", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetAnalyticsEngineInputsResponse)
		return soap_closesock(soap);
	tad__GetAnalyticsEngineInputsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetAnalyticsEngineInputsResponse->soap_get(soap, "tad:GetAnalyticsEngineInputsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetAnalyticsDeviceStreamUri(const char *endpoint, const char *soap_action, _tad__GetAnalyticsDeviceStreamUri *tad__GetAnalyticsDeviceStreamUri, _tad__GetAnalyticsDeviceStreamUriResponse *tad__GetAnalyticsDeviceStreamUriResponse)
{	struct soap *soap = this;
	struct __tad__GetAnalyticsDeviceStreamUri soap_tmp___tad__GetAnalyticsDeviceStreamUri;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsDeviceStreamUri";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetAnalyticsDeviceStreamUri.tad__GetAnalyticsDeviceStreamUri = tad__GetAnalyticsDeviceStreamUri;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetAnalyticsDeviceStreamUri(soap, &soap_tmp___tad__GetAnalyticsDeviceStreamUri);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetAnalyticsDeviceStreamUri(soap, &soap_tmp___tad__GetAnalyticsDeviceStreamUri, "-tad:GetAnalyticsDeviceStreamUri", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetAnalyticsDeviceStreamUri(soap, &soap_tmp___tad__GetAnalyticsDeviceStreamUri, "-tad:GetAnalyticsDeviceStreamUri", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetAnalyticsDeviceStreamUriResponse)
		return soap_closesock(soap);
	tad__GetAnalyticsDeviceStreamUriResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetAnalyticsDeviceStreamUriResponse->soap_get(soap, "tad:GetAnalyticsDeviceStreamUriResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetVideoAnalyticsConfiguration(const char *endpoint, const char *soap_action, _tad__GetVideoAnalyticsConfiguration *tad__GetVideoAnalyticsConfiguration, _tad__GetVideoAnalyticsConfigurationResponse *tad__GetVideoAnalyticsConfigurationResponse)
{	struct soap *soap = this;
	struct __tad__GetVideoAnalyticsConfiguration soap_tmp___tad__GetVideoAnalyticsConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetVideoAnalyticsConfiguration";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetVideoAnalyticsConfiguration.tad__GetVideoAnalyticsConfiguration = tad__GetVideoAnalyticsConfiguration;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetVideoAnalyticsConfiguration(soap, &soap_tmp___tad__GetVideoAnalyticsConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetVideoAnalyticsConfiguration(soap, &soap_tmp___tad__GetVideoAnalyticsConfiguration, "-tad:GetVideoAnalyticsConfiguration", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetVideoAnalyticsConfiguration(soap, &soap_tmp___tad__GetVideoAnalyticsConfiguration, "-tad:GetVideoAnalyticsConfiguration", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetVideoAnalyticsConfigurationResponse)
		return soap_closesock(soap);
	tad__GetVideoAnalyticsConfigurationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetVideoAnalyticsConfigurationResponse->soap_get(soap, "tad:GetVideoAnalyticsConfigurationResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::CreateAnalyticsEngineInputs(const char *endpoint, const char *soap_action, _tad__CreateAnalyticsEngineInputs *tad__CreateAnalyticsEngineInputs, _tad__CreateAnalyticsEngineInputsResponse *tad__CreateAnalyticsEngineInputsResponse)
{	struct soap *soap = this;
	struct __tad__CreateAnalyticsEngineInputs soap_tmp___tad__CreateAnalyticsEngineInputs;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/CreateAnalyticsEngineInputs";
	soap->encodingStyle = NULL;
	soap_tmp___tad__CreateAnalyticsEngineInputs.tad__CreateAnalyticsEngineInputs = tad__CreateAnalyticsEngineInputs;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__CreateAnalyticsEngineInputs(soap, &soap_tmp___tad__CreateAnalyticsEngineInputs);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__CreateAnalyticsEngineInputs(soap, &soap_tmp___tad__CreateAnalyticsEngineInputs, "-tad:CreateAnalyticsEngineInputs", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__CreateAnalyticsEngineInputs(soap, &soap_tmp___tad__CreateAnalyticsEngineInputs, "-tad:CreateAnalyticsEngineInputs", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__CreateAnalyticsEngineInputsResponse)
		return soap_closesock(soap);
	tad__CreateAnalyticsEngineInputsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__CreateAnalyticsEngineInputsResponse->soap_get(soap, "tad:CreateAnalyticsEngineInputsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::DeleteAnalyticsEngineInputs(const char *endpoint, const char *soap_action, _tad__DeleteAnalyticsEngineInputs *tad__DeleteAnalyticsEngineInputs, _tad__DeleteAnalyticsEngineInputsResponse *tad__DeleteAnalyticsEngineInputsResponse)
{	struct soap *soap = this;
	struct __tad__DeleteAnalyticsEngineInputs soap_tmp___tad__DeleteAnalyticsEngineInputs;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/DeleteAnalyticsEngineInputs";
	soap->encodingStyle = NULL;
	soap_tmp___tad__DeleteAnalyticsEngineInputs.tad__DeleteAnalyticsEngineInputs = tad__DeleteAnalyticsEngineInputs;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__DeleteAnalyticsEngineInputs(soap, &soap_tmp___tad__DeleteAnalyticsEngineInputs);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__DeleteAnalyticsEngineInputs(soap, &soap_tmp___tad__DeleteAnalyticsEngineInputs, "-tad:DeleteAnalyticsEngineInputs", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__DeleteAnalyticsEngineInputs(soap, &soap_tmp___tad__DeleteAnalyticsEngineInputs, "-tad:DeleteAnalyticsEngineInputs", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__DeleteAnalyticsEngineInputsResponse)
		return soap_closesock(soap);
	tad__DeleteAnalyticsEngineInputsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__DeleteAnalyticsEngineInputsResponse->soap_get(soap, "tad:DeleteAnalyticsEngineInputsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AnalyticsDeviceBindingProxy::GetAnalyticsState(const char *endpoint, const char *soap_action, _tad__GetAnalyticsState *tad__GetAnalyticsState, _tad__GetAnalyticsStateResponse *tad__GetAnalyticsStateResponse)
{	struct soap *soap = this;
	struct __tad__GetAnalyticsState soap_tmp___tad__GetAnalyticsState;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsState";
	soap->encodingStyle = NULL;
	soap_tmp___tad__GetAnalyticsState.tad__GetAnalyticsState = tad__GetAnalyticsState;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___tad__GetAnalyticsState(soap, &soap_tmp___tad__GetAnalyticsState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tad__GetAnalyticsState(soap, &soap_tmp___tad__GetAnalyticsState, "-tad:GetAnalyticsState", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tad__GetAnalyticsState(soap, &soap_tmp___tad__GetAnalyticsState, "-tad:GetAnalyticsState", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!tad__GetAnalyticsStateResponse)
		return soap_closesock(soap);
	tad__GetAnalyticsStateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tad__GetAnalyticsStateResponse->soap_get(soap, "tad:GetAnalyticsStateResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
