/* soapDeviceIOBindingProxy.h
   Generated by gSOAP 2.8.15 from ./onvif/onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapDeviceIOBindingProxy_H
#define soapDeviceIOBindingProxy_H
#include "soapH.h"

class SOAP_CMAC DeviceIOBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'DeviceIOBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	DeviceIOBindingProxy();
	/// Construct from another engine state
	DeviceIOBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	DeviceIOBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	DeviceIOBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	DeviceIOBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	DeviceIOBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~DeviceIOBindingProxy();
	/// Initializer used by constructors
	virtual	void DeviceIOBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities(_ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse *ns1__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, ns1__GetServiceCapabilities, ns1__GetServiceCapabilitiesResponse); }
	virtual	int GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse *ns1__GetServiceCapabilitiesResponse);

	/// Web service operation 'GetRelayOutputOptions' (returns error code or SOAP_OK)
	virtual	int GetRelayOutputOptions(_ns1__GetRelayOutputOptions *ns1__GetRelayOutputOptions, _ns1__GetRelayOutputOptionsResponse *ns1__GetRelayOutputOptionsResponse) { return this->GetRelayOutputOptions(NULL, NULL, ns1__GetRelayOutputOptions, ns1__GetRelayOutputOptionsResponse); }
	virtual	int GetRelayOutputOptions(const char *endpoint, const char *soap_action, _ns1__GetRelayOutputOptions *ns1__GetRelayOutputOptions, _ns1__GetRelayOutputOptionsResponse *ns1__GetRelayOutputOptionsResponse);

	/// Web service operation 'GetAudioSources' (returns error code or SOAP_OK)
	virtual	int GetAudioSources(_trt__GetAudioSources *trt__GetAudioSources, _trt__GetAudioSourcesResponse *trt__GetAudioSourcesResponse) { return this->GetAudioSources(NULL, NULL, trt__GetAudioSources, trt__GetAudioSourcesResponse); }
	virtual	int GetAudioSources(const char *endpoint, const char *soap_action, _trt__GetAudioSources *trt__GetAudioSources, _trt__GetAudioSourcesResponse *trt__GetAudioSourcesResponse);

	/// Web service operation 'GetAudioOutputs' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputs(_trt__GetAudioOutputs *trt__GetAudioOutputs, _trt__GetAudioOutputsResponse *trt__GetAudioOutputsResponse) { return this->GetAudioOutputs(NULL, NULL, trt__GetAudioOutputs, trt__GetAudioOutputsResponse); }
	virtual	int GetAudioOutputs(const char *endpoint, const char *soap_action, _trt__GetAudioOutputs *trt__GetAudioOutputs, _trt__GetAudioOutputsResponse *trt__GetAudioOutputsResponse);

	/// Web service operation 'GetVideoSources' (returns error code or SOAP_OK)
	virtual	int GetVideoSources(_trt__GetVideoSources *trt__GetVideoSources, _trt__GetVideoSourcesResponse *trt__GetVideoSourcesResponse) { return this->GetVideoSources(NULL, NULL, trt__GetVideoSources, trt__GetVideoSourcesResponse); }
	virtual	int GetVideoSources(const char *endpoint, const char *soap_action, _trt__GetVideoSources *trt__GetVideoSources, _trt__GetVideoSourcesResponse *trt__GetVideoSourcesResponse);

	/// Web service operation 'GetVideoOutputs' (returns error code or SOAP_OK)
	virtual	int GetVideoOutputs(_ns1__GetVideoOutputs *ns1__GetVideoOutputs, _ns1__GetVideoOutputsResponse *ns1__GetVideoOutputsResponse) { return this->GetVideoOutputs(NULL, NULL, ns1__GetVideoOutputs, ns1__GetVideoOutputsResponse); }
	virtual	int GetVideoOutputs(const char *endpoint, const char *soap_action, _ns1__GetVideoOutputs *ns1__GetVideoOutputs, _ns1__GetVideoOutputsResponse *ns1__GetVideoOutputsResponse);

	/// Web service operation 'GetVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfiguration(_ns1__GetVideoSourceConfiguration *ns1__GetVideoSourceConfiguration, _ns1__GetVideoSourceConfigurationResponse *ns1__GetVideoSourceConfigurationResponse) { return this->GetVideoSourceConfiguration(NULL, NULL, ns1__GetVideoSourceConfiguration, ns1__GetVideoSourceConfigurationResponse); }
	virtual	int GetVideoSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__GetVideoSourceConfiguration *ns1__GetVideoSourceConfiguration, _ns1__GetVideoSourceConfigurationResponse *ns1__GetVideoSourceConfigurationResponse);

	/// Web service operation 'GetVideoOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int GetVideoOutputConfiguration(_ns1__GetVideoOutputConfiguration *ns1__GetVideoOutputConfiguration, _ns1__GetVideoOutputConfigurationResponse *ns1__GetVideoOutputConfigurationResponse) { return this->GetVideoOutputConfiguration(NULL, NULL, ns1__GetVideoOutputConfiguration, ns1__GetVideoOutputConfigurationResponse); }
	virtual	int GetVideoOutputConfiguration(const char *endpoint, const char *soap_action, _ns1__GetVideoOutputConfiguration *ns1__GetVideoOutputConfiguration, _ns1__GetVideoOutputConfigurationResponse *ns1__GetVideoOutputConfigurationResponse);

	/// Web service operation 'GetAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfiguration(_ns1__GetAudioSourceConfiguration *ns1__GetAudioSourceConfiguration, _ns1__GetAudioSourceConfigurationResponse *ns1__GetAudioSourceConfigurationResponse) { return this->GetAudioSourceConfiguration(NULL, NULL, ns1__GetAudioSourceConfiguration, ns1__GetAudioSourceConfigurationResponse); }
	virtual	int GetAudioSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__GetAudioSourceConfiguration *ns1__GetAudioSourceConfiguration, _ns1__GetAudioSourceConfigurationResponse *ns1__GetAudioSourceConfigurationResponse);

	/// Web service operation 'GetAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfiguration(_ns1__GetAudioOutputConfiguration *ns1__GetAudioOutputConfiguration, _ns1__GetAudioOutputConfigurationResponse *ns1__GetAudioOutputConfigurationResponse) { return this->GetAudioOutputConfiguration(NULL, NULL, ns1__GetAudioOutputConfiguration, ns1__GetAudioOutputConfigurationResponse); }
	virtual	int GetAudioOutputConfiguration(const char *endpoint, const char *soap_action, _ns1__GetAudioOutputConfiguration *ns1__GetAudioOutputConfiguration, _ns1__GetAudioOutputConfigurationResponse *ns1__GetAudioOutputConfigurationResponse);

	/// Web service operation 'SetVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoSourceConfiguration(_ns1__SetVideoSourceConfiguration *ns1__SetVideoSourceConfiguration, _ns1__SetVideoSourceConfigurationResponse *ns1__SetVideoSourceConfigurationResponse) { return this->SetVideoSourceConfiguration(NULL, NULL, ns1__SetVideoSourceConfiguration, ns1__SetVideoSourceConfigurationResponse); }
	virtual	int SetVideoSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__SetVideoSourceConfiguration *ns1__SetVideoSourceConfiguration, _ns1__SetVideoSourceConfigurationResponse *ns1__SetVideoSourceConfigurationResponse);

	/// Web service operation 'SetVideoOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoOutputConfiguration(_ns1__SetVideoOutputConfiguration *ns1__SetVideoOutputConfiguration, _ns1__SetVideoOutputConfigurationResponse *ns1__SetVideoOutputConfigurationResponse) { return this->SetVideoOutputConfiguration(NULL, NULL, ns1__SetVideoOutputConfiguration, ns1__SetVideoOutputConfigurationResponse); }
	virtual	int SetVideoOutputConfiguration(const char *endpoint, const char *soap_action, _ns1__SetVideoOutputConfiguration *ns1__SetVideoOutputConfiguration, _ns1__SetVideoOutputConfigurationResponse *ns1__SetVideoOutputConfigurationResponse);

	/// Web service operation 'SetAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioSourceConfiguration(_ns1__SetAudioSourceConfiguration *ns1__SetAudioSourceConfiguration, _ns1__SetAudioSourceConfigurationResponse *ns1__SetAudioSourceConfigurationResponse) { return this->SetAudioSourceConfiguration(NULL, NULL, ns1__SetAudioSourceConfiguration, ns1__SetAudioSourceConfigurationResponse); }
	virtual	int SetAudioSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__SetAudioSourceConfiguration *ns1__SetAudioSourceConfiguration, _ns1__SetAudioSourceConfigurationResponse *ns1__SetAudioSourceConfigurationResponse);

	/// Web service operation 'SetAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioOutputConfiguration(_ns1__SetAudioOutputConfiguration *ns1__SetAudioOutputConfiguration, _ns1__SetAudioOutputConfigurationResponse *ns1__SetAudioOutputConfigurationResponse) { return this->SetAudioOutputConfiguration(NULL, NULL, ns1__SetAudioOutputConfiguration, ns1__SetAudioOutputConfigurationResponse); }
	virtual	int SetAudioOutputConfiguration(const char *endpoint, const char *soap_action, _ns1__SetAudioOutputConfiguration *ns1__SetAudioOutputConfiguration, _ns1__SetAudioOutputConfigurationResponse *ns1__SetAudioOutputConfigurationResponse);

	/// Web service operation 'GetVideoSourceConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfigurationOptions(_ns1__GetVideoSourceConfigurationOptions *ns1__GetVideoSourceConfigurationOptions, _ns1__GetVideoSourceConfigurationOptionsResponse *ns1__GetVideoSourceConfigurationOptionsResponse) { return this->GetVideoSourceConfigurationOptions(NULL, NULL, ns1__GetVideoSourceConfigurationOptions, ns1__GetVideoSourceConfigurationOptionsResponse); }
	virtual	int GetVideoSourceConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetVideoSourceConfigurationOptions *ns1__GetVideoSourceConfigurationOptions, _ns1__GetVideoSourceConfigurationOptionsResponse *ns1__GetVideoSourceConfigurationOptionsResponse);

	/// Web service operation 'GetVideoOutputConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetVideoOutputConfigurationOptions(_ns1__GetVideoOutputConfigurationOptions *ns1__GetVideoOutputConfigurationOptions, _ns1__GetVideoOutputConfigurationOptionsResponse *ns1__GetVideoOutputConfigurationOptionsResponse) { return this->GetVideoOutputConfigurationOptions(NULL, NULL, ns1__GetVideoOutputConfigurationOptions, ns1__GetVideoOutputConfigurationOptionsResponse); }
	virtual	int GetVideoOutputConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetVideoOutputConfigurationOptions *ns1__GetVideoOutputConfigurationOptions, _ns1__GetVideoOutputConfigurationOptionsResponse *ns1__GetVideoOutputConfigurationOptionsResponse);

	/// Web service operation 'GetAudioSourceConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfigurationOptions(_ns1__GetAudioSourceConfigurationOptions *ns1__GetAudioSourceConfigurationOptions, _ns1__GetAudioSourceConfigurationOptionsResponse *ns1__GetAudioSourceConfigurationOptionsResponse) { return this->GetAudioSourceConfigurationOptions(NULL, NULL, ns1__GetAudioSourceConfigurationOptions, ns1__GetAudioSourceConfigurationOptionsResponse); }
	virtual	int GetAudioSourceConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetAudioSourceConfigurationOptions *ns1__GetAudioSourceConfigurationOptions, _ns1__GetAudioSourceConfigurationOptionsResponse *ns1__GetAudioSourceConfigurationOptionsResponse);

	/// Web service operation 'GetAudioOutputConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfigurationOptions(_ns1__GetAudioOutputConfigurationOptions *ns1__GetAudioOutputConfigurationOptions, _ns1__GetAudioOutputConfigurationOptionsResponse *ns1__GetAudioOutputConfigurationOptionsResponse) { return this->GetAudioOutputConfigurationOptions(NULL, NULL, ns1__GetAudioOutputConfigurationOptions, ns1__GetAudioOutputConfigurationOptionsResponse); }
	virtual	int GetAudioOutputConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetAudioOutputConfigurationOptions *ns1__GetAudioOutputConfigurationOptions, _ns1__GetAudioOutputConfigurationOptionsResponse *ns1__GetAudioOutputConfigurationOptionsResponse);

	/// Web service operation 'GetRelayOutputs' (returns error code or SOAP_OK)
	virtual	int GetRelayOutputs(_tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse *tds__GetRelayOutputsResponse) { return this->GetRelayOutputs(NULL, NULL, tds__GetRelayOutputs, tds__GetRelayOutputsResponse); }
	virtual	int GetRelayOutputs(const char *endpoint, const char *soap_action, _tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse *tds__GetRelayOutputsResponse);

	/// Web service operation 'SetRelayOutputSettings' (returns error code or SOAP_OK)
	virtual	int SetRelayOutputSettings(_ns1__SetRelayOutputSettings *ns1__SetRelayOutputSettings, _ns1__SetRelayOutputSettingsResponse *ns1__SetRelayOutputSettingsResponse) { return this->SetRelayOutputSettings(NULL, NULL, ns1__SetRelayOutputSettings, ns1__SetRelayOutputSettingsResponse); }
	virtual	int SetRelayOutputSettings(const char *endpoint, const char *soap_action, _ns1__SetRelayOutputSettings *ns1__SetRelayOutputSettings, _ns1__SetRelayOutputSettingsResponse *ns1__SetRelayOutputSettingsResponse);

	/// Web service operation 'SetRelayOutputState' (returns error code or SOAP_OK)
	virtual	int SetRelayOutputState(_tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse *tds__SetRelayOutputStateResponse) { return this->SetRelayOutputState(NULL, NULL, tds__SetRelayOutputState, tds__SetRelayOutputStateResponse); }
	virtual	int SetRelayOutputState(const char *endpoint, const char *soap_action, _tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse *tds__SetRelayOutputStateResponse);

	/// Web service operation 'GetDigitalInputs' (returns error code or SOAP_OK)
	virtual	int GetDigitalInputs(_ns1__GetDigitalInputs *ns1__GetDigitalInputs, _ns1__GetDigitalInputsResponse *ns1__GetDigitalInputsResponse) { return this->GetDigitalInputs(NULL, NULL, ns1__GetDigitalInputs, ns1__GetDigitalInputsResponse); }
	virtual	int GetDigitalInputs(const char *endpoint, const char *soap_action, _ns1__GetDigitalInputs *ns1__GetDigitalInputs, _ns1__GetDigitalInputsResponse *ns1__GetDigitalInputsResponse);

	/// Web service operation 'GetSerialPorts' (returns error code or SOAP_OK)
	virtual	int GetSerialPorts(_ns1__GetSerialPorts *ns1__GetSerialPorts, _ns1__GetSerialPortsResponse *ns1__GetSerialPortsResponse) { return this->GetSerialPorts(NULL, NULL, ns1__GetSerialPorts, ns1__GetSerialPortsResponse); }
	virtual	int GetSerialPorts(const char *endpoint, const char *soap_action, _ns1__GetSerialPorts *ns1__GetSerialPorts, _ns1__GetSerialPortsResponse *ns1__GetSerialPortsResponse);

	/// Web service operation 'GetSerialPortConfiguration' (returns error code or SOAP_OK)
	virtual	int GetSerialPortConfiguration(_ns1__GetSerialPortConfiguration *ns1__GetSerialPortConfiguration, _ns1__GetSerialPortConfigurationResponse *ns1__GetSerialPortConfigurationResponse) { return this->GetSerialPortConfiguration(NULL, NULL, ns1__GetSerialPortConfiguration, ns1__GetSerialPortConfigurationResponse); }
	virtual	int GetSerialPortConfiguration(const char *endpoint, const char *soap_action, _ns1__GetSerialPortConfiguration *ns1__GetSerialPortConfiguration, _ns1__GetSerialPortConfigurationResponse *ns1__GetSerialPortConfigurationResponse);

	/// Web service operation 'SetSerialPortConfiguration' (returns error code or SOAP_OK)
	virtual	int SetSerialPortConfiguration(_ns1__SetSerialPortConfiguration *ns1__SetSerialPortConfiguration, _ns1__SetSerialPortConfigurationResponse *ns1__SetSerialPortConfigurationResponse) { return this->SetSerialPortConfiguration(NULL, NULL, ns1__SetSerialPortConfiguration, ns1__SetSerialPortConfigurationResponse); }
	virtual	int SetSerialPortConfiguration(const char *endpoint, const char *soap_action, _ns1__SetSerialPortConfiguration *ns1__SetSerialPortConfiguration, _ns1__SetSerialPortConfigurationResponse *ns1__SetSerialPortConfigurationResponse);

	/// Web service operation 'GetSerialPortConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetSerialPortConfigurationOptions(_ns1__GetSerialPortConfigurationOptions *ns1__GetSerialPortConfigurationOptions, _ns1__GetSerialPortConfigurationOptionsResponse *ns1__GetSerialPortConfigurationOptionsResponse) { return this->GetSerialPortConfigurationOptions(NULL, NULL, ns1__GetSerialPortConfigurationOptions, ns1__GetSerialPortConfigurationOptionsResponse); }
	virtual	int GetSerialPortConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetSerialPortConfigurationOptions *ns1__GetSerialPortConfigurationOptions, _ns1__GetSerialPortConfigurationOptionsResponse *ns1__GetSerialPortConfigurationOptionsResponse);

	/// Web service operation 'SendReceiveSerialCommand' (returns error code or SOAP_OK)
	virtual	int SendReceiveSerialCommand(_ns1__SendReceiveSerialCommand *ns1__SendReceiveSerialCommand, _ns1__SendReceiveSerialCommandResponse *ns1__SendReceiveSerialCommandResponse) { return this->SendReceiveSerialCommand(NULL, NULL, ns1__SendReceiveSerialCommand, ns1__SendReceiveSerialCommandResponse); }
	virtual	int SendReceiveSerialCommand(const char *endpoint, const char *soap_action, _ns1__SendReceiveSerialCommand *ns1__SendReceiveSerialCommand, _ns1__SendReceiveSerialCommandResponse *ns1__SendReceiveSerialCommandResponse);
};
#endif
